{ i3, i3status, xrandr, feh, py3status, lib, rofi-menugen, writeScript
, terminator, ipython, gnome_keyring, redshift, alot, networkmanagerapplet
, base16, rofi, rofi-pass, i3lock-fancy, xbacklight
, xcape
}:

let
  powerManagement = writeScript "rofi-power-management" ''
    #!${rofi-menugen}/bin/rofi-menugen
    #begin main
    prompt="Select:"
    add_exec 'Lock'         '${i3lock-fancy}/bin/i3lock-fancy'
    add_exec 'Sleep'        'systemctl suspend'
    add_exec 'Reboot'       'systemctl reboot'
    add_exec 'PowerOff'     'systemctl poweroff'
    #end main
  '';
  brigtnessManagement = writeScript "rofi-brigtness-management" ''
    #!${rofi-menugen}/bin/rofi-menugen
    #begin main
    prompt="Brigtness:"
    add_exec   "0" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 0"
    add_exec  "10" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 10"
    add_exec  "20" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 20"
    add_exec  "30" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 30"
    add_exec  "40" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 40"
    add_exec  "50" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 50"
    add_exec  "60" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 60"
    add_exec  "70" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 70"
    add_exec  "80" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 80"
    add_exec  "90" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 90"
    add_exec "100" "${xbacklight}/bin/xbacklight -time 500 -steps 30 -set 100"
    #end main
  '';

in ''
# This file has been auto-generated by i3-config-wizard(1).
# It will not be overwritten, so edit it as you like.
#
# Should you change your keyboard layout some time, delete
# this file and re-run i3-config-wizard(1).
#

# i3 config file (v4)
#
# Please see http://i3wm.org/docs/userguide.html for a complete reference!

set $mod Mod4

# Font for window titles. Will also be used by the bar unless a different font
# is used in the bar {} block below.
# This font is widely installed, provides lots of unicode glyphs, right-to-left
# text rendering and scalability on retina/hidpi displays (thanks to pango).
font pango:DejaVu Sans Mono 8
# Before i3 v4.8, we used to recommend this one as the default:
# font -misc-fixed-medium-r-normal--13-120-75-75-C-70-iso10646-1
# The font above is very space-efficient, that is, it looks good, sharp and
# clear in small sizes. However, its unicode glyph coverage is limited, the old
# X core fonts rendering does not support right-to-left and this being a bitmap
# font, it doesn’t scale on retina/hidpi displays.

# Use Mouse+$mod to drag floating windows to their wanted position
floating_modifier $mod

# start a terminal
bindsym $mod+Return exec ${terminator}/bin/terminator

# kill focused window
bindsym $mod+Shift+q kill

# start dmenu (a program launcher)
#bindsym $mod+r exec rofi -show run -opacity 75 -hide-scrollbar -lines 4 -fuzzy
bindsym $mod+r exec --no-startup-id ${i3}/bin/i3-dmenu-desktop --dmenu='${rofi}/bin/rofi -fuzzy -dmenu -p "run:"'
bindsym $mod+space exec --no-startup-id ${rofi}/bin/rofi -fuzzy -show window
bindsym $mod+Shift+p exec --no-startup-id ${rofi-pass}/bin/rofi-pass
bindsym $mod+Shift+o exec --no-startup-id ${powerManagement}
bindsym $mod+Shift+b exec --no-startup-id ${brigtnessManagement}


# change focus
bindsym $mod+j focus left
bindsym $mod+k focus down
bindsym $mod+l focus up
bindsym $mod+semicolon focus right

# alternatively, you can use the cursor keys:
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

# move focused window
bindsym $mod+Shift+j move left
bindsym $mod+Shift+k move down
bindsym $mod+Shift+l move up
bindsym $mod+Shift+semicolon move right

# alternatively, you can use the cursor keys:
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up
bindsym $mod+Shift+Right move right

# split in horizontal orientation
bindsym $mod+h split h

# split in vertical orientation
bindsym $mod+v split v

# enter fullscreen mode for the focused container
bindsym $mod+f fullscreen

# change container layout (stacked, tabbed, toggle split)
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# toggle tiling / floating
#bindsym $mod+Shift+space floating toggle

# change focus between tiling / floating windows
#bindsym $mod+space focus mode_toggle

# focus the parent container
bindsym $mod+a focus parent

# focus the child container
#bindsym $mod+d focus child

# switch to workspace
bindsym $mod+1 workspace 1
bindsym $mod+2 workspace 2
bindsym $mod+3 workspace 3
bindsym $mod+4 workspace 4
bindsym $mod+5 workspace 5
bindsym $mod+6 workspace 6
bindsym $mod+7 workspace 7
bindsym $mod+8 workspace 8
bindsym $mod+9 workspace 9
bindsym $mod+0 workspace 10

# move focused container to workspace
bindsym $mod+Shift+1 move container to workspace 1
bindsym $mod+Shift+2 move container to workspace 2
bindsym $mod+Shift+3 move container to workspace 3
bindsym $mod+Shift+4 move container to workspace 4
bindsym $mod+Shift+5 move container to workspace 5
bindsym $mod+Shift+6 move container to workspace 6
bindsym $mod+Shift+7 move container to workspace 7
bindsym $mod+Shift+8 move container to workspace 8
bindsym $mod+Shift+9 move container to workspace 9
bindsym $mod+Shift+0 move container to workspace 10

# lock screen
bindsym $mod+x exec '${i3lock-fancy}/bin/i3lock-fancy'

# reload the configuration file
bindsym $mod+Shift+c reload
# restart i3 inplace (preserves your layout/session, can be used to upgrade i3)
bindsym $mod+Shift+r restart
# exit i3 (logs you out of your X session)
bindsym $mod+Shift+e exec "i3-nagbar -t warning -m 'You pressed the exit shortcut. Do you really want to exit i3? This will end your X session.' -b 'Yes, exit i3' 'i3-msg exit'"

# resize window (you can also use the mouse for that)
mode "resize" {
        # These bindings trigger as soon as you enter the resize mode

        # Pressing left will shrink the window’s width.
        # Pressing right will grow the window’s width.
        # Pressing up will shrink the window’s height.
        # Pressing down will grow the window’s height.
        bindsym j resize shrink width 10 px or 10 ppt
        bindsym k resize grow height 10 px or 10 ppt
        bindsym l resize shrink height 10 px or 10 ppt
        bindsym semicolon resize grow width 10 px or 10 ppt

        # same bindings, but for the arrow keys
        bindsym Left resize shrink width 10 px or 10 ppt
        bindsym Down resize grow height 10 px or 10 ppt
        bindsym Up resize shrink height 10 px or 10 ppt
        bindsym Right resize grow width 10 px or 10 ppt

        # back to normal: Enter or Escape
        bindsym Return mode "default"
        bindsym Escape mode "default"
}

bindsym $mod+b mode "resize"


bindsym XF86AudioRaiseVolume exec amixer -q set Master 2dB+ unmute
bindsym XF86AudioLowerVolume exec amixer -q set Master 2dB- unmute
bindsym XF86AudioMute exec amixer -q set Master toggle
bindcode 232 exec xbacklight -dec 10
bindcode 233 exec xbacklight -inc 10


# Start i3bar to display a workspace bar (plus the system information i3status
# finds out, if available)
bar {
        status_command i3status
}

for_window [class="^Spotify$"] floating enable
for_window [class="^Spotify Premium$"] floating enable
for_window [class="Firefox"] floating enable


exec --no-startup-id ${networkmanagerapplet}/bin/nm-applet
exec --no-startup-id ${xcape}/bin/xcape -e 'Control_L=Escape;Shift_R=parenright;Shift_L=parenleft'
exec --no-startup-id ${feh}/bin/feh --bg-scale $HOME/.nixos-config/wallpaper.jpg
exec xset r rate 200 50
''
