# This file has been generated by node2nix 1.1.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "nomnom-1.8.1" = {
      name = "nomnom";
      packageName = "nomnom";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nomnom/-/nomnom-1.8.1.tgz";
        sha1 = "2151f722472ba79e50a76fc125bb8c8f2e4dc2a7";
      };
    };
    "JSV-4.0.2" = {
      name = "JSV";
      packageName = "JSV";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSV/-/JSV-4.0.2.tgz";
        sha1 = "d077f6825571f82132f9dffaed587b4029feff57";
      };
    };
    "underscore-1.6.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz";
        sha1 = "8b38b10cacdef63337b8b24e4ff86d45aea529a8";
      };
    };
    "chalk-0.4.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-0.4.0.tgz";
        sha1 = "5199a3ddcd0c1efe23bc08c1b027b06176e0c64f";
      };
    };
    "has-color-0.1.7" = {
      name = "has-color";
      packageName = "has-color";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-color/-/has-color-0.1.7.tgz";
        sha1 = "67144a5260c34fc3cca677d041daf52fe7b78b2f";
      };
    };
    "ansi-styles-1.0.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-1.0.0.tgz";
        sha1 = "cb102df1c56f5123eab8b67cd7b98027a0279178";
      };
    };
    "strip-ansi-0.1.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-0.1.1.tgz";
        sha1 = "39e8a98d044d150660abe4a6808acf70bb7bc991";
      };
    };
    "camelcase-1.2.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz";
        sha1 = "9bb5304d2e0b56698b2c758b08a3eaa9daa58a39";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "char-spinner-1.0.1" = {
      name = "char-spinner";
      packageName = "char-spinner";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/char-spinner/-/char-spinner-1.0.1.tgz";
        sha1 = "e6ea67bd247e107112983b7ab0479ed362800081";
      };
    };
    "debug-2.6.6" = {
      name = "debug";
      packageName = "debug";
      version = "2.6.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.6.6.tgz";
        sha1 = "a9fa6fbe9ca43cf1e79f73b75c0189cbb7d6db5a";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "npm-4.3.0" = {
      name = "npm";
      packageName = "npm";
      version = "4.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm/-/npm-4.3.0.tgz";
        sha1 = "78e97142408c8383bff10a0e4036e9f77f00ce28";
      };
    };
    "npm-package-arg-4.2.1" = {
      name = "npm-package-arg";
      packageName = "npm-package-arg";
      version = "4.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-package-arg/-/npm-package-arg-4.2.1.tgz";
        sha1 = "593303fdea85f7c422775f17f9eb7670f680e3ec";
      };
    };
    "ramda-0.18.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.18.0.tgz";
        sha1 = "c6e3c5d4b9ab1f7906727fdeeb039152a85d4db3";
      };
    };
    "ramda-fantasy-0.4.1" = {
      name = "ramda-fantasy";
      packageName = "ramda-fantasy";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda-fantasy/-/ramda-fantasy-0.4.1.tgz";
        sha1 = "5977f7b97195f74866aef3ff8d0dbbb2483dfa01";
      };
    };
    "repl.history-0.1.4" = {
      name = "repl.history";
      packageName = "repl.history";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/repl.history/-/repl.history-0.1.4.tgz";
        sha1 = "80367171f3781d6e4299c71758c253097f5d5832";
      };
    };
    "sanctuary-0.7.1" = {
      name = "sanctuary";
      packageName = "sanctuary";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanctuary/-/sanctuary-0.7.1.tgz";
        sha1 = "76961ae291666f339419526ccdd2266618edc293";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.1.1" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.1.1.tgz";
        sha1 = "c3b33ab5ee360d86e0e628f0468ae7ef27d654df";
      };
    };
    "ms-0.7.3" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.3.tgz";
        sha1 = "708155a5e44e33f5fd0fc53e81d0d40a91be1fff";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.7" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.7.tgz";
        sha1 = "3effc3c50e000531fb720eaff80f0ae8ef23cf59";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "JSONStream-1.3.1" = {
      name = "JSONStream";
      packageName = "JSONStream";
      version = "1.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSONStream/-/JSONStream-1.3.1.tgz";
        sha1 = "707f761e01dae9e16f1bcf93703b78c70966579a";
      };
    };
    "abbrev-1.0.9" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.0.9.tgz";
        sha1 = "91b4792588a7738c25f35dd6f63752a2f8776135";
      };
    };
    "ansicolors-0.3.2" = {
      name = "ansicolors";
      packageName = "ansicolors";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansicolors/-/ansicolors-0.3.2.tgz";
        sha1 = "665597de86a9ffe3aa9bfbe6cae5c6ea426b4979";
      };
    };
    "ansistyles-0.1.3" = {
      name = "ansistyles";
      packageName = "ansistyles";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansistyles/-/ansistyles-0.1.3.tgz";
        sha1 = "5de60415bda071bb37127854c864f41b23254539";
      };
    };
    "aproba-1.1.1" = {
      name = "aproba";
      packageName = "aproba";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/aproba/-/aproba-1.1.1.tgz";
        sha1 = "95d3600f07710aa0e9298c726ad5ecf2eacbabab";
      };
    };
    "archy-1.0.0" = {
      name = "archy";
      packageName = "archy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archy/-/archy-1.0.0.tgz";
        sha1 = "f9c8c13757cc1dd7bc379ac77b2c62a5c2868c40";
      };
    };
    "asap-2.0.5" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.5.tgz";
        sha1 = "522765b50c3510490e52d7dcfe085ef9ba96958f";
      };
    };
    "chownr-1.0.1" = {
      name = "chownr";
      packageName = "chownr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-1.0.1.tgz";
        sha1 = "e2a75042a9551908bebd25b8523d5f9769d79181";
      };
    };
    "cmd-shim-2.0.2" = {
      name = "cmd-shim";
      packageName = "cmd-shim";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cmd-shim/-/cmd-shim-2.0.2.tgz";
        sha1 = "6fcbda99483a8fd15d7d30a196ca69d688a2efdb";
      };
    };
    "columnify-1.5.4" = {
      name = "columnify";
      packageName = "columnify";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/columnify/-/columnify-1.5.4.tgz";
        sha1 = "4737ddf1c7b69a8a7c340570782e947eec8e78bb";
      };
    };
    "config-chain-1.1.11" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.11.tgz";
        sha1 = "aba09747dfbe4c3e70e766a6e41586e1859fc6f2";
      };
    };
    "dezalgo-1.0.3" = {
      name = "dezalgo";
      packageName = "dezalgo";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dezalgo/-/dezalgo-1.0.3.tgz";
        sha1 = "7f742de066fc748bc8db820569dddce49bf0d456";
      };
    };
    "editor-1.0.0" = {
      name = "editor";
      packageName = "editor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/editor/-/editor-1.0.0.tgz";
        sha1 = "60c7f87bd62bcc6a894fa8ccd6afb7823a24f742";
      };
    };
    "fs-vacuum-1.2.10" = {
      name = "fs-vacuum";
      packageName = "fs-vacuum";
      version = "1.2.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-vacuum/-/fs-vacuum-1.2.10.tgz";
        sha1 = "b7629bec07a4031a2548fdf99f5ecf1cc8b31e36";
      };
    };
    "fs-write-stream-atomic-1.0.10" = {
      name = "fs-write-stream-atomic";
      packageName = "fs-write-stream-atomic";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-write-stream-atomic/-/fs-write-stream-atomic-1.0.10.tgz";
        sha1 = "b47df53493ef911df75731e70a9ded0189db40c9";
      };
    };
    "fstream-1.0.11" = {
      name = "fstream";
      packageName = "fstream";
      version = "1.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream/-/fstream-1.0.11.tgz";
        sha1 = "5c1fb1f117477114f0632a0eb4b71b3cb0fd3171";
      };
    };
    "fstream-npm-1.2.0" = {
      name = "fstream-npm";
      packageName = "fstream-npm";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream-npm/-/fstream-npm-1.2.0.tgz";
        sha1 = "d2c3c89101346982d64e57091c38487bda916fce";
      };
    };
    "glob-7.1.1" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.1.tgz";
        sha1 = "805211df04faaf1c63a3600306cdf5ade50b2ec8";
      };
    };
    "graceful-fs-4.1.11" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.11.tgz";
        sha1 = "0e8bdfe4d1ddb8854d64e04ea7c00e2a026e5658";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "hosted-git-info-2.2.0" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.2.0.tgz";
        sha1 = "7a0d097863d886c0fabbdcd37bf1758d8becf8a5";
      };
    };
    "iferr-0.1.5" = {
      name = "iferr";
      packageName = "iferr";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/iferr/-/iferr-0.1.5.tgz";
        sha1 = "c60eed69e6d8fdb6b3104a1fcbca1c192dc5b501";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "init-package-json-1.9.6" = {
      name = "init-package-json";
      packageName = "init-package-json";
      version = "1.9.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/init-package-json/-/init-package-json-1.9.6.tgz";
        sha1 = "789fc2b74466a4952b9ea77c0575bc78ebd60a61";
      };
    };
    "lazy-property-1.0.0" = {
      name = "lazy-property";
      packageName = "lazy-property";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lazy-property/-/lazy-property-1.0.0.tgz";
        sha1 = "84ddc4b370679ba8bd4cdcfa4c06b43d57111147";
      };
    };
    "lockfile-1.0.3" = {
      name = "lockfile";
      packageName = "lockfile";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lockfile/-/lockfile-1.0.3.tgz";
        sha1 = "2638fc39a0331e9cac1a04b71799931c9c50df79";
      };
    };
    "lodash._baseuniq-4.6.0" = {
      name = "lodash._baseuniq";
      packageName = "lodash._baseuniq";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._baseuniq/-/lodash._baseuniq-4.6.0.tgz";
        sha1 = "0ebb44e456814af7905c6212fa2c9b2d51b841e8";
      };
    };
    "lodash.clonedeep-4.5.0" = {
      name = "lodash.clonedeep";
      packageName = "lodash.clonedeep";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.clonedeep/-/lodash.clonedeep-4.5.0.tgz";
        sha1 = "e23f3f9c4f8fbdde872529c1071857a086e5ccef";
      };
    };
    "lodash.union-4.6.0" = {
      name = "lodash.union";
      packageName = "lodash.union";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.union/-/lodash.union-4.6.0.tgz";
        sha1 = "48bb5088409f16f1821666641c44dd1aaae3cd88";
      };
    };
    "lodash.uniq-4.5.0" = {
      name = "lodash.uniq";
      packageName = "lodash.uniq";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.uniq/-/lodash.uniq-4.5.0.tgz";
        sha1 = "d0225373aeb652adc1bc82e4945339a842754773";
      };
    };
    "lodash.without-4.4.0" = {
      name = "lodash.without";
      packageName = "lodash.without";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.without/-/lodash.without-4.4.0.tgz";
        sha1 = "3cd4574a00b67bae373a94b748772640507b7aac";
      };
    };
    "mississippi-1.3.0" = {
      name = "mississippi";
      packageName = "mississippi";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mississippi/-/mississippi-1.3.0.tgz";
        sha1 = "d201583eb12327e3c5c1642a404a9cacf94e34f5";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "node-gyp-3.5.0" = {
      name = "node-gyp";
      packageName = "node-gyp";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp/-/node-gyp-3.5.0.tgz";
        sha1 = "a8fe5e611d079ec16348a3eb960e78e11c85274a";
      };
    };
    "nopt-4.0.1" = {
      name = "nopt";
      packageName = "nopt";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-4.0.1.tgz";
        sha1 = "d0d4685afd5415193c8c7505602d0d17cd64474d";
      };
    };
    "normalize-git-url-3.0.2" = {
      name = "normalize-git-url";
      packageName = "normalize-git-url";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-git-url/-/normalize-git-url-3.0.2.tgz";
        sha1 = "8e5f14be0bdaedb73e07200310aa416c27350fc4";
      };
    };
    "normalize-package-data-2.3.8" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.3.8.tgz";
        sha1 = "d819eda2a9dedbd1ffa563ea4071d936782295bb";
      };
    };
    "npm-cache-filename-1.0.2" = {
      name = "npm-cache-filename";
      packageName = "npm-cache-filename";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-cache-filename/-/npm-cache-filename-1.0.2.tgz";
        sha1 = "ded306c5b0bfc870a9e9faf823bc5f283e05ae11";
      };
    };
    "npm-install-checks-3.0.0" = {
      name = "npm-install-checks";
      packageName = "npm-install-checks";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-install-checks/-/npm-install-checks-3.0.0.tgz";
        sha1 = "d4aecdfd51a53e3723b7b2f93b2ee28e307bc0d7";
      };
    };
    "npm-registry-client-7.4.6" = {
      name = "npm-registry-client";
      packageName = "npm-registry-client";
      version = "7.4.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-registry-client/-/npm-registry-client-7.4.6.tgz";
        sha1 = "0aa7c55f18631b941b7b80a7aa501bfcb8b19717";
      };
    };
    "npm-user-validate-0.1.5" = {
      name = "npm-user-validate";
      packageName = "npm-user-validate";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-user-validate/-/npm-user-validate-0.1.5.tgz";
        sha1 = "52465d50c2d20294a57125b996baedbf56c5004b";
      };
    };
    "npmlog-4.0.2" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-4.0.2.tgz";
        sha1 = "d03950e0e78ce1527ba26d2a7592e9348ac3e75f";
      };
    };
    "opener-1.4.3" = {
      name = "opener";
      packageName = "opener";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/opener/-/opener-1.4.3.tgz";
        sha1 = "5c6da2c5d7e5831e8ffa3964950f8d6674ac90b8";
      };
    };
    "osenv-0.1.4" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.4.tgz";
        sha1 = "42fe6d5953df06c8064be6f176c3d05aaaa34644";
      };
    };
    "path-is-inside-1.0.2" = {
      name = "path-is-inside";
      packageName = "path-is-inside";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-inside/-/path-is-inside-1.0.2.tgz";
        sha1 = "365417dede44430d1c11af61027facf074bdfc53";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha1 = "b3da19bd052431a97671d44a42634adf710b40c4";
      };
    };
    "read-cmd-shim-1.0.1" = {
      name = "read-cmd-shim";
      packageName = "read-cmd-shim";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-cmd-shim/-/read-cmd-shim-1.0.1.tgz";
        sha1 = "2d5d157786a37c055d22077c32c53f8329e91c7b";
      };
    };
    "read-installed-4.0.3" = {
      name = "read-installed";
      packageName = "read-installed";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-installed/-/read-installed-4.0.3.tgz";
        sha1 = "ff9b8b67f187d1e4c29b9feb31f6b223acd19067";
      };
    };
    "read-package-json-2.0.5" = {
      name = "read-package-json";
      packageName = "read-package-json";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-package-json/-/read-package-json-2.0.5.tgz";
        sha1 = "f93a64e641529df68a08c64de46389e8a3f88845";
      };
    };
    "read-package-tree-5.1.5" = {
      name = "read-package-tree";
      packageName = "read-package-tree";
      version = "5.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-package-tree/-/read-package-tree-5.1.5.tgz";
        sha1 = "ace7e6381c7684f970aaa98fc7c5d2b666addab6";
      };
    };
    "readable-stream-2.2.9" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.2.9.tgz";
        sha1 = "cf78ec6f4a6d1eb43d26488cac97f042e74b7fc8";
      };
    };
    "realize-package-specifier-3.0.3" = {
      name = "realize-package-specifier";
      packageName = "realize-package-specifier";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/realize-package-specifier/-/realize-package-specifier-3.0.3.tgz";
        sha1 = "d0def882952b8de3f67eba5e91199661271f41f4";
      };
    };
    "request-2.79.0" = {
      name = "request";
      packageName = "request";
      version = "2.79.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.79.0.tgz";
        sha1 = "4dfe5bf6be8b8cdc37fcf93e04b65577722710de";
      };
    };
    "retry-0.10.1" = {
      name = "retry";
      packageName = "retry";
      version = "0.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.10.1.tgz";
        sha1 = "e76388d217992c252750241d3d3956fed98d8ff4";
      };
    };
    "rimraf-2.5.4" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz";
        sha1 = "96800093cbf1a0c86bd95b4625467535c29dfa04";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "sha-2.0.1" = {
      name = "sha";
      packageName = "sha";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha/-/sha-2.0.1.tgz";
        sha1 = "6030822fbd2c9823949f8f72ed6411ee5cf25aae";
      };
    };
    "slide-1.1.6" = {
      name = "slide";
      packageName = "slide";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/slide/-/slide-1.1.6.tgz";
        sha1 = "56eb027d65b4d2dce6cb2e2d32c4d4afc9e1d707";
      };
    };
    "sorted-object-2.0.1" = {
      name = "sorted-object";
      packageName = "sorted-object";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sorted-object/-/sorted-object-2.0.1.tgz";
        sha1 = "7d631f4bd3a798a24af1dffcfbfe83337a5df5fc";
      };
    };
    "sorted-union-stream-2.1.3" = {
      name = "sorted-union-stream";
      packageName = "sorted-union-stream";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/sorted-union-stream/-/sorted-union-stream-2.1.3.tgz";
        sha1 = "c7794c7e077880052ff71a8d4a2dbb4a9a638ac7";
      };
    };
    "tar-2.2.1" = {
      name = "tar";
      packageName = "tar";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-2.2.1.tgz";
        sha1 = "8e4d2a256c0e2185c6b18ad694aec968b83cb1d1";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "uid-number-0.0.6" = {
      name = "uid-number";
      packageName = "uid-number";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-number/-/uid-number-0.0.6.tgz";
        sha1 = "0ea10e8035e8eb5b8e4449f06da1c730663baa81";
      };
    };
    "umask-1.1.0" = {
      name = "umask";
      packageName = "umask";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/umask/-/umask-1.1.0.tgz";
        sha1 = "f29cebf01df517912bb58ff9c4e50fde8e33320d";
      };
    };
    "unique-filename-1.1.0" = {
      name = "unique-filename";
      packageName = "unique-filename";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-filename/-/unique-filename-1.1.0.tgz";
        sha1 = "d05f2fe4032560871f30e93cbe735eea201514f3";
      };
    };
    "unpipe-1.0.0" = {
      name = "unpipe";
      packageName = "unpipe";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unpipe/-/unpipe-1.0.0.tgz";
        sha1 = "b2bf4ee8514aae6165b4817829d21b2ef49904ec";
      };
    };
    "uuid-3.0.1" = {
      name = "uuid";
      packageName = "uuid";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/uuid/-/uuid-3.0.1.tgz";
        sha1 = "6544bba2dfda8c1cf17e629a3a305e2bb1fee6c1";
      };
    };
    "validate-npm-package-name-2.2.2" = {
      name = "validate-npm-package-name";
      packageName = "validate-npm-package-name";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-name/-/validate-npm-package-name-2.2.2.tgz";
        sha1 = "f65695b22f7324442019a3c7fa39a6e7fd299085";
      };
    };
    "which-1.2.14" = {
      name = "which";
      packageName = "which";
      version = "1.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.2.14.tgz";
        sha1 = "9a87c4378f03e827cecaf1acdf56c736c01c14e5";
      };
    };
    "write-file-atomic-1.3.4" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.3.4.tgz";
        sha1 = "f807a4f0b1d9e913ae7a48112e6cc3af1991b45f";
      };
    };
    "debuglog-1.0.1" = {
      name = "debuglog";
      packageName = "debuglog";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debuglog/-/debuglog-1.0.1.tgz";
        sha1 = "aa24ffb9ac3df9a2351837cfb2d279360cd78492";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "lodash._baseindexof-3.1.0" = {
      name = "lodash._baseindexof";
      packageName = "lodash._baseindexof";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._baseindexof/-/lodash._baseindexof-3.1.0.tgz";
        sha1 = "fe52b53a1c6761e42618d654e4a25789ed61822c";
      };
    };
    "lodash._bindcallback-3.0.1" = {
      name = "lodash._bindcallback";
      packageName = "lodash._bindcallback";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._bindcallback/-/lodash._bindcallback-3.0.1.tgz";
        sha1 = "e531c27644cf8b57a99e17ed95b35c748789392e";
      };
    };
    "lodash._cacheindexof-3.0.2" = {
      name = "lodash._cacheindexof";
      packageName = "lodash._cacheindexof";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._cacheindexof/-/lodash._cacheindexof-3.0.2.tgz";
        sha1 = "3dc69ac82498d2ee5e3ce56091bafd2adc7bde92";
      };
    };
    "lodash._createcache-3.1.2" = {
      name = "lodash._createcache";
      packageName = "lodash._createcache";
      version = "3.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._createcache/-/lodash._createcache-3.1.2.tgz";
        sha1 = "56d6a064017625e79ebca6b8018e17440bdcf093";
      };
    };
    "lodash._getnative-3.9.1" = {
      name = "lodash._getnative";
      packageName = "lodash._getnative";
      version = "3.9.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._getnative/-/lodash._getnative-3.9.1.tgz";
        sha1 = "570bc7dede46d61cdcde687d65d3eecbaa3aaff5";
      };
    };
    "lodash.restparam-3.6.1" = {
      name = "lodash.restparam";
      packageName = "lodash.restparam";
      version = "3.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.restparam/-/lodash.restparam-3.6.1.tgz";
        sha1 = "936a4e309ef330a7645ed4145986c85ae5b20805";
      };
    };
    "readdir-scoped-modules-1.0.2" = {
      name = "readdir-scoped-modules";
      packageName = "readdir-scoped-modules";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdir-scoped-modules/-/readdir-scoped-modules-1.0.2.tgz";
        sha1 = "9fafa37d286be5d92cbaebdee030dc9b5f406747";
      };
    };
    "validate-npm-package-license-3.0.1" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.1.tgz";
        sha1 = "2804babe712ad3379459acfbe24746ab2c303fbc";
      };
    };
    "jsonparse-1.3.0" = {
      name = "jsonparse";
      packageName = "jsonparse";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonparse/-/jsonparse-1.3.0.tgz";
        sha1 = "85fc245b1d9259acc6941960b905adf64e7de0e8";
      };
    };
    "through-2.3.8" = {
      name = "through";
      packageName = "through";
      version = "2.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/through/-/through-2.3.8.tgz";
        sha1 = "0dd4c9ffaabc357960b1b724115d7e0e86a2e1f5";
      };
    };
    "wcwidth-1.0.1" = {
      name = "wcwidth";
      packageName = "wcwidth";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wcwidth/-/wcwidth-1.0.1.tgz";
        sha1 = "f0b0dcf915bc5ff1528afadb2c0e17b532da2fe8";
      };
    };
    "defaults-1.0.3" = {
      name = "defaults";
      packageName = "defaults";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/defaults/-/defaults-1.0.3.tgz";
        sha1 = "c656051e9817d9ff08ed881477f3fe4019f3ef7d";
      };
    };
    "clone-1.0.2" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.2.tgz";
        sha1 = "260b7a99ebb1edfe247538175f783243cb19d149";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "fstream-ignore-1.0.5" = {
      name = "fstream-ignore";
      packageName = "fstream-ignore";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream-ignore/-/fstream-ignore-1.0.5.tgz";
        sha1 = "9c31dae34767018fe1d249b24dada67d092da105";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "promzard-0.3.0" = {
      name = "promzard";
      packageName = "promzard";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promzard/-/promzard-0.3.0.tgz";
        sha1 = "26a5d6ee8c7dee4cb12208305acfb93ba382a9ee";
      };
    };
    "validate-npm-package-name-3.0.0" = {
      name = "validate-npm-package-name";
      packageName = "validate-npm-package-name";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-name/-/validate-npm-package-name-3.0.0.tgz";
        sha1 = "5fa912d81eb7d0c74afc140de7317f0ca7df437e";
      };
    };
    "builtins-1.0.3" = {
      name = "builtins";
      packageName = "builtins";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-1.0.3.tgz";
        sha1 = "cb94faeb61c8696451db36534e1422f94f0aee88";
      };
    };
    "lodash._createset-4.0.3" = {
      name = "lodash._createset";
      packageName = "lodash._createset";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._createset/-/lodash._createset-4.0.3.tgz";
        sha1 = "0f4659fbb09d75194fa9e2b88a6644d363c9fe26";
      };
    };
    "lodash._root-3.0.1" = {
      name = "lodash._root";
      packageName = "lodash._root";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash._root/-/lodash._root-3.0.1.tgz";
        sha1 = "fba1c4524c19ee9a5f8136b4609f017cf4ded692";
      };
    };
    "concat-stream-1.6.0" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.6.0.tgz";
        sha1 = "0aac662fd52be78964d5532f694784e70110acf7";
      };
    };
    "duplexify-3.5.0" = {
      name = "duplexify";
      packageName = "duplexify";
      version = "3.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/duplexify/-/duplexify-3.5.0.tgz";
        sha1 = "1aa773002e1578457e9d9d4a50b0ccaaebcbd604";
      };
    };
    "end-of-stream-1.4.0" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.4.0.tgz";
        sha1 = "7a90d833efda6cfa6eac0f4949dbb0fad3a63206";
      };
    };
    "flush-write-stream-1.0.2" = {
      name = "flush-write-stream";
      packageName = "flush-write-stream";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/flush-write-stream/-/flush-write-stream-1.0.2.tgz";
        sha1 = "c81b90d8746766f1a609a46809946c45dd8ae417";
      };
    };
    "from2-2.3.0" = {
      name = "from2";
      packageName = "from2";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/from2/-/from2-2.3.0.tgz";
        sha1 = "8bfb5502bde4a4d36cfdeea007fcca21d7e382af";
      };
    };
    "parallel-transform-1.1.0" = {
      name = "parallel-transform";
      packageName = "parallel-transform";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/parallel-transform/-/parallel-transform-1.1.0.tgz";
        sha1 = "d410f065b05da23081fcd10f28854c29bda33b06";
      };
    };
    "pump-1.0.2" = {
      name = "pump";
      packageName = "pump";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/pump/-/pump-1.0.2.tgz";
        sha1 = "3b3ee6512f94f0e575538c17995f9f16990a5d51";
      };
    };
    "pumpify-1.3.5" = {
      name = "pumpify";
      packageName = "pumpify";
      version = "1.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/pumpify/-/pumpify-1.3.5.tgz";
        sha1 = "1b671c619940abcaeac0ad0e3a3c164be760993b";
      };
    };
    "stream-each-1.2.0" = {
      name = "stream-each";
      packageName = "stream-each";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-each/-/stream-each-1.2.0.tgz";
        sha1 = "1e95d47573f580d814dc0ff8cd0f66f1ce53c991";
      };
    };
    "through2-2.0.3" = {
      name = "through2";
      packageName = "through2";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/through2/-/through2-2.0.3.tgz";
        sha1 = "0004569b37c7c74ba39c43f3ced78d1ad94140be";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "end-of-stream-1.0.0" = {
      name = "end-of-stream";
      packageName = "end-of-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/end-of-stream/-/end-of-stream-1.0.0.tgz";
        sha1 = "d4596e702734a93e40e9af864319eabd99ff2f0e";
      };
    };
    "stream-shift-1.0.0" = {
      name = "stream-shift";
      packageName = "stream-shift";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-shift/-/stream-shift-1.0.0.tgz";
        sha1 = "d5c752825e5367e786f78e18e445ea223a155952";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "cyclist-0.2.2" = {
      name = "cyclist";
      packageName = "cyclist";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cyclist/-/cyclist-0.2.2.tgz";
        sha1 = "1b33792e11e914a2fd6d6ed6447464444e5fa640";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "are-we-there-yet-1.1.4" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.4.tgz";
        sha1 = "bb5dca382bb94f05e15194373d16fd3ba1ca110d";
      };
    };
    "console-control-strings-1.1.0" = {
      name = "console-control-strings";
      packageName = "console-control-strings";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/console-control-strings/-/console-control-strings-1.1.0.tgz";
        sha1 = "3d7cf4464db6446ea644bf4b39507f9851008e8e";
      };
    };
    "gauge-2.7.4" = {
      name = "gauge";
      packageName = "gauge";
      version = "2.7.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-2.7.4.tgz";
        sha1 = "2c03405c7538c39d7eb37b317022e325fb018bf7";
      };
    };
    "set-blocking-2.0.0" = {
      name = "set-blocking";
      packageName = "set-blocking";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/set-blocking/-/set-blocking-2.0.0.tgz";
        sha1 = "045f9782d011ae9a6803ddd382b24392b3d890f7";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "object-assign-4.1.1" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.1.tgz";
        sha1 = "2109adc7965887cfc05cbbd442cac8bfbb360863";
      };
    };
    "signal-exit-3.0.2" = {
      name = "signal-exit";
      packageName = "signal-exit";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/signal-exit/-/signal-exit-3.0.2.tgz";
        sha1 = "b5fdc08f1287ea1178628e415e25132b73646c6d";
      };
    };
    "string-width-1.0.2" = {
      name = "string-width";
      packageName = "string-width";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/string-width/-/string-width-1.0.2.tgz";
        sha1 = "118bdf5b8cdc51a2a7e70d211e07e2b0b9b107d3";
      };
    };
    "wide-align-1.1.0" = {
      name = "wide-align";
      packageName = "wide-align";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/wide-align/-/wide-align-1.1.0.tgz";
        sha1 = "40edde802a71fea1f070da3e62dcda2e7add96ad";
      };
    };
    "code-point-at-1.1.0" = {
      name = "code-point-at";
      packageName = "code-point-at";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/code-point-at/-/code-point-at-1.1.0.tgz";
        sha1 = "0d070b4d043a5bea33a2f1a40e2edb3d9a4ccf77";
      };
    };
    "is-fullwidth-code-point-1.0.0" = {
      name = "is-fullwidth-code-point";
      packageName = "is-fullwidth-code-point";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-fullwidth-code-point/-/is-fullwidth-code-point-1.0.0.tgz";
        sha1 = "ef9e31386f031a7f0d643af82fde50c457ef00cb";
      };
    };
    "number-is-nan-1.0.1" = {
      name = "number-is-nan";
      packageName = "number-is-nan";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/number-is-nan/-/number-is-nan-1.0.1.tgz";
        sha1 = "097b602b53422a522c1afb8790318336941a011d";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "mute-stream-0.0.7" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.7.tgz";
        sha1 = "3075ce93bc21b8fab43e1bc4da7e8115ed1e7bab";
      };
    };
    "util-extend-1.0.3" = {
      name = "util-extend";
      packageName = "util-extend";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-extend/-/util-extend-1.0.3.tgz";
        sha1 = "a7c216d267545169637b3b6edc6ca9119e2ff93f";
      };
    };
    "json-parse-helpfulerror-1.0.3" = {
      name = "json-parse-helpfulerror";
      packageName = "json-parse-helpfulerror";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-helpfulerror/-/json-parse-helpfulerror-1.0.3.tgz";
        sha1 = "13f14ce02eed4e981297b64eb9e3b932e2dd13dc";
      };
    };
    "jju-1.3.0" = {
      name = "jju";
      packageName = "jju";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jju/-/jju-1.3.0.tgz";
        sha1 = "dadd9ef01924bc728b03f2f7979bdbd62f7a2aaa";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-1.0.0" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-1.0.0.tgz";
        sha1 = "f06f41157b664d86069f84bdbdc9b0d8ab281667";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "aws4-1.6.0" = {
      name = "aws4";
      packageName = "aws4";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws4/-/aws4-1.6.0.tgz";
        sha1 = "83ef5ca860b2b32e4a0deedee8c771b9db57471e";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "extend-3.0.1" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.1.tgz";
        sha1 = "a755ea7bc1adfcc5a31ce7e762dbaadc5e636444";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-2.1.4" = {
      name = "form-data";
      packageName = "form-data";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-2.1.4.tgz";
        sha1 = "33c183acf193276ecaa98143a69e94bfee1750d1";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "http-signature-1.1.1" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-1.1.1.tgz";
        sha1 = "df72e267066cd0ac67fb76adf8e134a8fbcf91bf";
      };
    };
    "is-typedarray-1.0.0" = {
      name = "is-typedarray";
      packageName = "is-typedarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-typedarray/-/is-typedarray-1.0.0.tgz";
        sha1 = "e479c80858df0c1b11ddda6940f96011fcda4a9a";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.15" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.15.tgz";
        sha1 = "a4ebf5064094569237b8cf70046776d09fc92aed";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "qs-6.3.2" = {
      name = "qs";
      packageName = "qs";
      version = "6.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-6.3.2.tgz";
        sha1 = "e75bd5f6e268122a2a0e0bda630b2550c166502c";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "tough-cookie-2.3.2" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.3.2.tgz";
        sha1 = "f081f76e4c85720e6c37a5faced737150d84072a";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "asynckit-0.4.0" = {
      name = "asynckit";
      packageName = "asynckit";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/asynckit/-/asynckit-0.4.0.tgz";
        sha1 = "c79ed97f7f34cb8f2ba1bc9790bcc366474b4b79";
      };
    };
    "commander-2.9.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
        sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
      };
    };
    "is-my-json-valid-2.16.0" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.16.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.16.0.tgz";
        sha1 = "f079dd9bfdae65ee2038aae8acbc86ab109e3693";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-4.0.1" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-4.0.1.tgz";
        sha1 = "4fd92cb34e0e9db3c89c8622ecf51f9b978c6cb9";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "assert-plus-0.2.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.2.0.tgz";
        sha1 = "d74e1b87e7affc0db8aadb7021f3fe48101ab234";
      };
    };
    "jsprim-1.4.0" = {
      name = "jsprim";
      packageName = "jsprim";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsprim/-/jsprim-1.4.0.tgz";
        sha1 = "a3b87e40298d8c380552d8cc7628a0bb95a22918";
      };
    };
    "sshpk-1.13.0" = {
      name = "sshpk";
      packageName = "sshpk";
      version = "1.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sshpk/-/sshpk-1.13.0.tgz";
        sha1 = "ff2a3e4fd04497555fed97b39a0fd82fafb3a33c";
      };
    };
    "assert-plus-1.0.0" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-1.0.0.tgz";
        sha1 = "f12e0f3c5d77b0b1cdd9146942e4e96c1e4dd525";
      };
    };
    "extsprintf-1.0.2" = {
      name = "extsprintf";
      packageName = "extsprintf";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extsprintf/-/extsprintf-1.0.2.tgz";
        sha1 = "e1080e0658e300b06294990cc70e1502235fd550";
      };
    };
    "json-schema-0.2.3" = {
      name = "json-schema";
      packageName = "json-schema";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema/-/json-schema-0.2.3.tgz";
        sha1 = "b480c892e59a2f05954ce727bd3f2a4e882f9e13";
      };
    };
    "verror-1.3.6" = {
      name = "verror";
      packageName = "verror";
      version = "1.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/verror/-/verror-1.3.6.tgz";
        sha1 = "cff5df12946d297d2baaefaa2689e25be01c005c";
      };
    };
    "asn1-0.2.3" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.2.3.tgz";
        sha1 = "dac8787713c9966849fc8180777ebe9c1ddf3b86";
      };
    };
    "dashdash-1.14.1" = {
      name = "dashdash";
      packageName = "dashdash";
      version = "1.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/dashdash/-/dashdash-1.14.1.tgz";
        sha1 = "853cfa0f7cbe2fed5de20326b8dd581035f6e2f0";
      };
    };
    "getpass-0.1.7" = {
      name = "getpass";
      packageName = "getpass";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/getpass/-/getpass-0.1.7.tgz";
        sha1 = "5eff8e3e684d569ae4cb2b1282604e8ba62149fa";
      };
    };
    "jsbn-0.1.1" = {
      name = "jsbn";
      packageName = "jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsbn/-/jsbn-0.1.1.tgz";
        sha1 = "a5e654c2e5a2deb5f201d96cefbca80c0ef2f513";
      };
    };
    "tweetnacl-0.14.5" = {
      name = "tweetnacl";
      packageName = "tweetnacl";
      version = "0.14.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/tweetnacl/-/tweetnacl-0.14.5.tgz";
        sha1 = "5ae68177f192d4456269d108afa93ff8743f4f64";
      };
    };
    "jodid25519-1.0.2" = {
      name = "jodid25519";
      packageName = "jodid25519";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jodid25519/-/jodid25519-1.0.2.tgz";
        sha1 = "06d4912255093419477d425633606e0e90782967";
      };
    };
    "ecc-jsbn-0.1.1" = {
      name = "ecc-jsbn";
      packageName = "ecc-jsbn";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ecc-jsbn/-/ecc-jsbn-0.1.1.tgz";
        sha1 = "0fc73a9ed5f0d53c38193398523ef7e543777505";
      };
    };
    "bcrypt-pbkdf-1.0.1" = {
      name = "bcrypt-pbkdf";
      packageName = "bcrypt-pbkdf";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bcrypt-pbkdf/-/bcrypt-pbkdf-1.0.1.tgz";
        sha1 = "63bc5dcb61331b92bc05fd528953c33462a06f8d";
      };
    };
    "mime-db-1.27.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.27.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.27.0.tgz";
        sha1 = "820f572296bbd20ec25ed55e5b5de869e5436eb1";
      };
    };
    "punycode-1.4.1" = {
      name = "punycode";
      packageName = "punycode";
      version = "1.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode/-/punycode-1.4.1.tgz";
        sha1 = "c0d5a63b2718800ad8e1eb0fa5269c84dd41845e";
      };
    };
    "from2-1.3.0" = {
      name = "from2";
      packageName = "from2";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/from2/-/from2-1.3.0.tgz";
        sha1 = "88413baaa5f9a597cfde9221d86986cd3c061dfd";
      };
    };
    "stream-iterate-1.2.0" = {
      name = "stream-iterate";
      packageName = "stream-iterate";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/stream-iterate/-/stream-iterate-1.2.0.tgz";
        sha1 = "2bd7c77296c1702a46488b8ad41f79865eecd4e1";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "block-stream-0.0.9" = {
      name = "block-stream";
      packageName = "block-stream";
      version = "0.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/block-stream/-/block-stream-0.0.9.tgz";
        sha1 = "13ebfe778a03205cfe03751481ebb4b3300c126a";
      };
    };
    "unique-slug-2.0.0" = {
      name = "unique-slug";
      packageName = "unique-slug";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unique-slug/-/unique-slug-2.0.0.tgz";
        sha1 = "db6676e7c7cc0629878ff196097c78855ae9f4ab";
      };
    };
    "builtins-0.0.7" = {
      name = "builtins";
      packageName = "builtins";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-0.0.7.tgz";
        sha1 = "355219cd6cf18dbe7c01cc7fd2dce765cfdc549a";
      };
    };
    "isexe-2.0.0" = {
      name = "isexe";
      packageName = "isexe";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-2.0.0.tgz";
        sha1 = "e8fbf374dc556ff8947a10dcb0572d633f2cfa10";
      };
    };
    "spdx-correct-1.0.2" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-1.0.2.tgz";
        sha1 = "4b3073d933ff51f3912f03ac5519498a4150db40";
      };
    };
    "spdx-expression-parse-1.0.4" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.4.tgz";
        sha1 = "9bdf2f20e1f40ed447fbe273266191fced51626c";
      };
    };
    "spdx-license-ids-1.2.2" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz";
        sha1 = "c9df7a3424594ade6bd11900d596696dc06bac57";
      };
    };
    "ramda-0.17.1" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.17.1.tgz";
        sha1 = "4c198147d3ab54e8c15255f11730e2116f6e6073";
      };
    };
    "acorn-4.0.11" = {
      name = "acorn";
      packageName = "acorn";
      version = "4.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-4.0.11.tgz";
        sha1 = "edcda3bd937e7556410d42ed5860f67399c794c0";
      };
    };
    "enhanced-resolve-2.3.0" = {
      name = "enhanced-resolve";
      packageName = "enhanced-resolve";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-2.3.0.tgz";
        sha1 = "a115c32504b6302e85a76269d7a57ccdd962e359";
      };
    };
    "resolve-from-2.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-2.0.0.tgz";
        sha1 = "9480ab20e94ffa1d9e80a804c7ea147611966b57";
      };
    };
    "tapable-0.2.6" = {
      name = "tapable";
      packageName = "tapable";
      version = "0.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/tapable/-/tapable-0.2.6.tgz";
        sha1 = "206be8e188860b514425375e6f1ae89bfb01fd8d";
      };
    };
    "memory-fs-0.3.0" = {
      name = "memory-fs";
      packageName = "memory-fs";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/memory-fs/-/memory-fs-0.3.0.tgz";
        sha1 = "7bcc6b629e3a43e871d7e29aca6ae8a7f15cbb20";
      };
    };
    "errno-0.1.4" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.4.tgz";
        sha1 = "b896e23a9e5e8ba33871fc996abd3635fc9a1c7d";
      };
    };
    "prr-0.0.0" = {
      name = "prr";
      packageName = "prr";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-0.0.0.tgz";
        sha1 = "1a84b85908325501411853d0081ee3fa86e2926a";
      };
    };
  };
in
{
  jsonlint = nodeEnv.buildNodePackage {
    name = "jsonlint";
    packageName = "jsonlint";
    version = "1.6.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/jsonlint/-/jsonlint-1.6.2.tgz";
      sha1 = "5737045085f55eb455c68b1ff4ebc01bd50e8830";
    };
    dependencies = [
      sources."nomnom-1.8.1"
      sources."JSV-4.0.2"
      sources."underscore-1.6.0"
      sources."chalk-0.4.0"
      sources."has-color-0.1.7"
      sources."ansi-styles-1.0.0"
      sources."strip-ansi-0.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Validate JSON";
      homepage = http://zaach.github.com/jsonlint/;
    };
    production = true;
  };
  replem = nodeEnv.buildNodePackage {
    name = "replem";
    packageName = "replem";
    version = "2.0.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/replem/-/replem-2.0.1.tgz";
      sha1 = "0d48f40797f752dfdf3fdb323f2ca12716abcb9c";
    };
    dependencies = [
      sources."camelcase-1.2.1"
      sources."chalk-1.1.3"
      sources."char-spinner-1.0.1"
      sources."debug-2.6.6"
      sources."glob-5.0.15"
      sources."minimist-1.2.0"
      (sources."npm-4.3.0" // {
        dependencies = [
          sources."glob-7.1.1"
        ];
      })
      sources."npm-package-arg-4.2.1"
      sources."ramda-0.18.0"
      (sources."ramda-fantasy-0.4.1" // {
        dependencies = [
          sources."ramda-0.17.1"
        ];
      })
      sources."repl.history-0.1.4"
      (sources."sanctuary-0.7.1" // {
        dependencies = [
          sources."ramda-0.17.1"
        ];
      })
      sources."xtend-4.0.1"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.1.1"
      sources."ms-0.7.3"
      sources."inflight-1.0.6"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.3"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.7"
      sources."balanced-match-0.4.2"
      sources."concat-map-0.0.1"
      sources."JSONStream-1.3.1"
      sources."abbrev-1.0.9"
      sources."ansicolors-0.3.2"
      sources."ansistyles-0.1.3"
      sources."aproba-1.1.1"
      sources."archy-1.0.0"
      sources."asap-2.0.5"
      sources."chownr-1.0.1"
      sources."cmd-shim-2.0.2"
      sources."columnify-1.5.4"
      sources."config-chain-1.1.11"
      sources."dezalgo-1.0.3"
      sources."editor-1.0.0"
      sources."fs-vacuum-1.2.10"
      sources."fs-write-stream-atomic-1.0.10"
      sources."fstream-1.0.11"
      sources."fstream-npm-1.2.0"
      sources."graceful-fs-4.1.11"
      sources."has-unicode-2.0.1"
      sources."hosted-git-info-2.2.0"
      sources."iferr-0.1.5"
      sources."ini-1.3.4"
      (sources."init-package-json-1.9.6" // {
        dependencies = [
          sources."glob-7.1.1"
          sources."validate-npm-package-name-3.0.0"
        ];
      })
      sources."lazy-property-1.0.0"
      sources."lockfile-1.0.3"
      sources."lodash._baseuniq-4.6.0"
      sources."lodash.clonedeep-4.5.0"
      sources."lodash.union-4.6.0"
      sources."lodash.uniq-4.5.0"
      sources."lodash.without-4.4.0"
      sources."mississippi-1.3.0"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      (sources."node-gyp-3.5.0" // {
        dependencies = [
          sources."glob-7.1.1"
          sources."nopt-3.0.6"
        ];
      })
      sources."nopt-4.0.1"
      sources."normalize-git-url-3.0.2"
      sources."normalize-package-data-2.3.8"
      sources."npm-cache-filename-1.0.2"
      sources."npm-install-checks-3.0.0"
      sources."npm-registry-client-7.4.6"
      sources."npm-user-validate-0.1.5"
      sources."npmlog-4.0.2"
      sources."opener-1.4.3"
      sources."osenv-0.1.4"
      sources."path-is-inside-1.0.2"
      sources."read-1.0.7"
      sources."read-cmd-shim-1.0.1"
      sources."read-installed-4.0.3"
      (sources."read-package-json-2.0.5" // {
        dependencies = [
          sources."glob-7.1.1"
        ];
      })
      sources."read-package-tree-5.1.5"
      sources."readable-stream-2.2.9"
      sources."realize-package-specifier-3.0.3"
      sources."request-2.79.0"
      sources."retry-0.10.1"
      (sources."rimraf-2.5.4" // {
        dependencies = [
          sources."glob-7.1.1"
        ];
      })
      sources."semver-5.3.0"
      sources."sha-2.0.1"
      sources."slide-1.1.6"
      sources."sorted-object-2.0.1"
      (sources."sorted-union-stream-2.1.3" // {
        dependencies = [
          sources."from2-1.3.0"
          sources."readable-stream-1.1.14"
          sources."isarray-0.0.1"
          sources."string_decoder-0.10.31"
        ];
      })
      sources."tar-2.2.1"
      sources."text-table-0.2.0"
      sources."uid-number-0.0.6"
      sources."umask-1.1.0"
      sources."unique-filename-1.1.0"
      sources."unpipe-1.0.0"
      sources."uuid-3.0.1"
      (sources."validate-npm-package-name-2.2.2" // {
        dependencies = [
          sources."builtins-0.0.7"
        ];
      })
      sources."which-1.2.14"
      sources."write-file-atomic-1.3.4"
      sources."debuglog-1.0.1"
      sources."imurmurhash-0.1.4"
      sources."lodash._baseindexof-3.1.0"
      sources."lodash._bindcallback-3.0.1"
      sources."lodash._cacheindexof-3.0.2"
      sources."lodash._createcache-3.1.2"
      sources."lodash._getnative-3.9.1"
      sources."lodash.restparam-3.6.1"
      sources."readdir-scoped-modules-1.0.2"
      sources."validate-npm-package-license-3.0.1"
      sources."jsonparse-1.3.0"
      sources."through-2.3.8"
      sources."wcwidth-1.0.1"
      sources."defaults-1.0.3"
      sources."clone-1.0.2"
      sources."proto-list-1.2.4"
      sources."fstream-ignore-1.0.5"
      sources."fs.realpath-1.0.0"
      sources."promzard-0.3.0"
      sources."builtins-1.0.3"
      sources."lodash._createset-4.0.3"
      sources."lodash._root-3.0.1"
      sources."concat-stream-1.6.0"
      (sources."duplexify-3.5.0" // {
        dependencies = [
          sources."end-of-stream-1.0.0"
          sources."once-1.3.3"
        ];
      })
      sources."end-of-stream-1.4.0"
      sources."flush-write-stream-1.0.2"
      sources."from2-2.3.0"
      sources."parallel-transform-1.1.0"
      sources."pump-1.0.2"
      sources."pumpify-1.3.5"
      sources."stream-each-1.2.0"
      sources."through2-2.0.3"
      sources."typedarray-0.0.6"
      sources."stream-shift-1.0.0"
      sources."cyclist-0.2.2"
      sources."is-builtin-module-1.0.0"
      sources."builtin-modules-1.1.1"
      sources."are-we-there-yet-1.1.4"
      sources."console-control-strings-1.1.0"
      sources."gauge-2.7.4"
      sources."set-blocking-2.0.0"
      sources."delegates-1.0.0"
      sources."object-assign-4.1.1"
      sources."signal-exit-3.0.2"
      sources."string-width-1.0.2"
      sources."wide-align-1.1.0"
      sources."code-point-at-1.1.0"
      sources."is-fullwidth-code-point-1.0.0"
      sources."number-is-nan-1.0.1"
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."mute-stream-0.0.7"
      sources."util-extend-1.0.3"
      sources."json-parse-helpfulerror-1.0.3"
      sources."jju-1.3.0"
      sources."buffer-shims-1.0.0"
      sources."core-util-is-1.0.2"
      sources."isarray-1.0.0"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-1.0.0"
      sources."util-deprecate-1.0.2"
      sources."aws-sign2-0.6.0"
      sources."aws4-1.6.0"
      sources."caseless-0.11.0"
      sources."combined-stream-1.0.5"
      sources."extend-3.0.1"
      sources."forever-agent-0.6.1"
      sources."form-data-2.1.4"
      sources."har-validator-2.0.6"
      sources."hawk-3.1.3"
      sources."http-signature-1.1.1"
      sources."is-typedarray-1.0.0"
      sources."isstream-0.1.2"
      sources."json-stringify-safe-5.0.1"
      sources."mime-types-2.1.15"
      sources."oauth-sign-0.8.2"
      sources."qs-6.3.2"
      sources."stringstream-0.0.5"
      sources."tough-cookie-2.3.2"
      sources."tunnel-agent-0.4.3"
      sources."delayed-stream-1.0.0"
      sources."asynckit-0.4.0"
      sources."commander-2.9.0"
      sources."is-my-json-valid-2.16.0"
      sources."pinkie-promise-2.0.1"
      sources."graceful-readlink-1.0.1"
      sources."generate-function-2.0.0"
      sources."generate-object-property-1.2.0"
      sources."jsonpointer-4.0.1"
      sources."is-property-1.0.2"
      sources."pinkie-2.0.4"
      sources."hoek-2.16.3"
      sources."boom-2.10.1"
      sources."cryptiles-2.0.5"
      sources."sntp-1.0.9"
      sources."assert-plus-0.2.0"
      (sources."jsprim-1.4.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."sshpk-1.13.0" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."extsprintf-1.0.2"
      sources."json-schema-0.2.3"
      sources."verror-1.3.6"
      sources."asn1-0.2.3"
      (sources."dashdash-1.14.1" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      (sources."getpass-0.1.7" // {
        dependencies = [
          sources."assert-plus-1.0.0"
        ];
      })
      sources."jsbn-0.1.1"
      sources."tweetnacl-0.14.5"
      sources."jodid25519-1.0.2"
      sources."ecc-jsbn-0.1.1"
      sources."bcrypt-pbkdf-1.0.1"
      sources."mime-db-1.27.0"
      sources."punycode-1.4.1"
      sources."stream-iterate-1.2.0"
      sources."block-stream-0.0.9"
      sources."unique-slug-2.0.0"
      sources."isexe-2.0.0"
      sources."spdx-correct-1.0.2"
      sources."spdx-expression-parse-1.0.4"
      sources."spdx-license-ids-1.2.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Instantly try npm modules in REPL environment";
      homepage = "https://github.com/raine/replem#readme";
      license = "ISC";
    };
    production = true;
  };
  tern = nodeEnv.buildNodePackage {
    name = "tern";
    packageName = "tern";
    version = "0.21.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/tern/-/tern-0.21.0.tgz";
      sha1 = "809c87a826e112494398cf8894f7c2d1b3464eb7";
    };
    dependencies = [
      sources."acorn-4.0.11"
      sources."enhanced-resolve-2.3.0"
      sources."glob-7.1.1"
      sources."minimatch-3.0.3"
      sources."resolve-from-2.0.0"
      sources."tapable-0.2.6"
      sources."memory-fs-0.3.0"
      sources."graceful-fs-4.1.11"
      sources."object-assign-4.1.1"
      sources."errno-0.1.4"
      sources."readable-stream-2.2.9"
      sources."prr-0.0.0"
      sources."buffer-shims-1.0.0"
      sources."core-util-is-1.0.2"
      sources."isarray-1.0.0"
      sources."inherits-2.0.3"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-1.0.0"
      sources."util-deprecate-1.0.2"
      sources."fs.realpath-1.0.0"
      sources."inflight-1.0.6"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.7"
      sources."balanced-match-0.4.2"
      sources."concat-map-0.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A JavaScript code analyzer for deep, cross-editor language support";
      homepage = "https://github.com/ternjs/tern#readme";
      license = "MIT";
    };
    production = true;
  };
  elm-oracle = nodeEnv.buildNodePackage {
    name = "elm-oracle";
    packageName = "elm-oracle";
    version = "1.1.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/elm-oracle/-/elm-oracle-1.1.1.tgz";
      sha1 = "61f6d783221b4ad08e7d101d678b9d5a67d3961c";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Query for information about values in elm source files.";
      homepage = "https://github.com/ElmCast/elm-oracle#readme";
      license = "BSD-3-Clause";
    };
    production = true;
  };
}