# This file has been generated by node2nix 1.1.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "nomnom-1.8.1" = {
      name = "nomnom";
      packageName = "nomnom";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nomnom/-/nomnom-1.8.1.tgz";
        sha1 = "2151f722472ba79e50a76fc125bb8c8f2e4dc2a7";
      };
    };
    "JSV-4.0.2" = {
      name = "JSV";
      packageName = "JSV";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/JSV/-/JSV-4.0.2.tgz";
        sha1 = "d077f6825571f82132f9dffaed587b4029feff57";
      };
    };
    "underscore-1.6.0" = {
      name = "underscore";
      packageName = "underscore";
      version = "1.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/underscore/-/underscore-1.6.0.tgz";
        sha1 = "8b38b10cacdef63337b8b24e4ff86d45aea529a8";
      };
    };
    "chalk-0.4.0" = {
      name = "chalk";
      packageName = "chalk";
      version = "0.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-0.4.0.tgz";
        sha1 = "5199a3ddcd0c1efe23bc08c1b027b06176e0c64f";
      };
    };
    "has-color-0.1.7" = {
      name = "has-color";
      packageName = "has-color";
      version = "0.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-color/-/has-color-0.1.7.tgz";
        sha1 = "67144a5260c34fc3cca677d041daf52fe7b78b2f";
      };
    };
    "ansi-styles-1.0.0" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-1.0.0.tgz";
        sha1 = "cb102df1c56f5123eab8b67cd7b98027a0279178";
      };
    };
    "strip-ansi-0.1.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-0.1.1.tgz";
        sha1 = "39e8a98d044d150660abe4a6808acf70bb7bc991";
      };
    };
    "camelcase-1.2.1" = {
      name = "camelcase";
      packageName = "camelcase";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/camelcase/-/camelcase-1.2.1.tgz";
        sha1 = "9bb5304d2e0b56698b2c758b08a3eaa9daa58a39";
      };
    };
    "chalk-1.1.3" = {
      name = "chalk";
      packageName = "chalk";
      version = "1.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/chalk/-/chalk-1.1.3.tgz";
        sha1 = "a8115c55e4a702fe4d150abd3872822a7e09fc98";
      };
    };
    "char-spinner-1.0.1" = {
      name = "char-spinner";
      packageName = "char-spinner";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/char-spinner/-/char-spinner-1.0.1.tgz";
        sha1 = "e6ea67bd247e107112983b7ab0479ed362800081";
      };
    };
    "debug-2.2.0" = {
      name = "debug";
      packageName = "debug";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-2.2.0.tgz";
        sha1 = "f87057e995b1a1f6ae6a4960664137bc56f039da";
      };
    };
    "glob-5.0.15" = {
      name = "glob";
      packageName = "glob";
      version = "5.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-5.0.15.tgz";
        sha1 = "1bc936b9e02f4a603fcc222ecf7633d30b8b93b1";
      };
    };
    "minimist-1.2.0" = {
      name = "minimist";
      packageName = "minimist";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-1.2.0.tgz";
        sha1 = "a35008b20f41383eec1fb914f4cd5df79a264284";
      };
    };
    "npm-2.14.11" = {
      name = "npm";
      packageName = "npm";
      version = "2.14.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm/-/npm-2.14.11.tgz";
        sha1 = "3a566e59b41e01f05e34a458eb1e4a9e0ec2ef65";
      };
    };
    "npm-package-arg-4.2.0" = {
      name = "npm-package-arg";
      packageName = "npm-package-arg";
      version = "4.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-package-arg/-/npm-package-arg-4.2.0.tgz";
        sha1 = "809bc61cabf54bd5ff94f6165c89ba8ee88c115c";
      };
    };
    "ramda-0.18.0" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.18.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.18.0.tgz";
        sha1 = "c6e3c5d4b9ab1f7906727fdeeb039152a85d4db3";
      };
    };
    "ramda-fantasy-0.4.1" = {
      name = "ramda-fantasy";
      packageName = "ramda-fantasy";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda-fantasy/-/ramda-fantasy-0.4.1.tgz";
        sha1 = "5977f7b97195f74866aef3ff8d0dbbb2483dfa01";
      };
    };
    "repl.history-0.1.3" = {
      name = "repl.history";
      packageName = "repl.history";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/repl.history/-/repl.history-0.1.3.tgz";
        sha1 = "ae017e34de2cd73bbe748a90d585383055710cdd";
      };
    };
    "sanctuary-0.7.1" = {
      name = "sanctuary";
      packageName = "sanctuary";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sanctuary/-/sanctuary-0.7.1.tgz";
        sha1 = "76961ae291666f339419526ccdd2266618edc293";
      };
    };
    "xtend-4.0.1" = {
      name = "xtend";
      packageName = "xtend";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/xtend/-/xtend-4.0.1.tgz";
        sha1 = "a5c6d532be656e23db820efb943a1f04998d63af";
      };
    };
    "ansi-styles-2.2.1" = {
      name = "ansi-styles";
      packageName = "ansi-styles";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.1.tgz";
        sha1 = "b432dd3358b634cf75e1e4664368240533c1ddbe";
      };
    };
    "escape-string-regexp-1.0.5" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-1.0.5.tgz";
        sha1 = "1b61c0562190a8dff6ae3bb2cf0200ca130b86d4";
      };
    };
    "has-ansi-2.0.0" = {
      name = "has-ansi";
      packageName = "has-ansi";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-ansi/-/has-ansi-2.0.0.tgz";
        sha1 = "34f5049ce1ecdf2b0649af3ef24e45ed35416d91";
      };
    };
    "strip-ansi-3.0.1" = {
      name = "strip-ansi";
      packageName = "strip-ansi";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/strip-ansi/-/strip-ansi-3.0.1.tgz";
        sha1 = "6a385fb8853d952d5ff05d0e8aaf94278dc63dcf";
      };
    };
    "supports-color-2.0.0" = {
      name = "supports-color";
      packageName = "supports-color";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/supports-color/-/supports-color-2.0.0.tgz";
        sha1 = "535d045ce6b6363fa40117084629995e9df324c7";
      };
    };
    "ansi-regex-2.0.0" = {
      name = "ansi-regex";
      packageName = "ansi-regex";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi-regex/-/ansi-regex-2.0.0.tgz";
        sha1 = "c5061b6e0ef8a81775e50f5d66151bf6bf371107";
      };
    };
    "ms-0.7.1" = {
      name = "ms";
      packageName = "ms";
      version = "0.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-0.7.1.tgz";
        sha1 = "9cd13c03adbff25b65effde7ce864ee952017098";
      };
    };
    "inflight-1.0.5" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.5.tgz";
        sha1 = "db3204cd5a9de2e6cd890b85c6e2f66bcf4f620a";
      };
    };
    "inherits-2.0.3" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.3.tgz";
        sha1 = "633c2c83e3da42a502f52466022480f4208261de";
      };
    };
    "minimatch-3.0.3" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.3.tgz";
        sha1 = "2a4e4090b96b2db06a9d7df01055a62a77c9b774";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
    "brace-expansion-1.1.6" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.6.tgz";
        sha1 = "7197d7eaa9b87e648390ea61fc66c84427420df9";
      };
    };
    "balanced-match-0.4.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "0.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-0.4.2.tgz";
        sha1 = "cb3f3e3c732dc0f01ee70b403f302e61d7709838";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "abbrev-1.0.9" = {
      name = "abbrev";
      packageName = "abbrev";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/abbrev/-/abbrev-1.0.9.tgz";
        sha1 = "91b4792588a7738c25f35dd6f63752a2f8776135";
      };
    };
    "ansi-0.3.1" = {
      name = "ansi";
      packageName = "ansi";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansi/-/ansi-0.3.1.tgz";
        sha1 = "0c42d4fb17160d5a9af1e484bace1c66922c1b21";
      };
    };
    "ansicolors-0.3.2" = {
      name = "ansicolors";
      packageName = "ansicolors";
      version = "0.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansicolors/-/ansicolors-0.3.2.tgz";
        sha1 = "665597de86a9ffe3aa9bfbe6cae5c6ea426b4979";
      };
    };
    "ansistyles-0.1.3" = {
      name = "ansistyles";
      packageName = "ansistyles";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ansistyles/-/ansistyles-0.1.3.tgz";
        sha1 = "5de60415bda071bb37127854c864f41b23254539";
      };
    };
    "archy-1.0.0" = {
      name = "archy";
      packageName = "archy";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/archy/-/archy-1.0.0.tgz";
        sha1 = "f9c8c13757cc1dd7bc379ac77b2c62a5c2868c40";
      };
    };
    "async-some-1.0.2" = {
      name = "async-some";
      packageName = "async-some";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/async-some/-/async-some-1.0.2.tgz";
        sha1 = "4d8a81620d5958791b5b98f802d3207776e95509";
      };
    };
    "block-stream-0.0.8" = {
      name = "block-stream";
      packageName = "block-stream";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/block-stream/-/block-stream-0.0.8.tgz";
        sha1 = "0688f46da2bbf9cff0c4f68225a0cb95cbe8a46b";
      };
    };
    "chmodr-1.0.2" = {
      name = "chmodr";
      packageName = "chmodr";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/chmodr/-/chmodr-1.0.2.tgz";
        sha1 = "04662b932d0f02ec66deaa2b0ea42811968e3eb9";
      };
    };
    "chownr-1.0.1" = {
      name = "chownr";
      packageName = "chownr";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/chownr/-/chownr-1.0.1.tgz";
        sha1 = "e2a75042a9551908bebd25b8523d5f9769d79181";
      };
    };
    "cmd-shim-2.0.2" = {
      name = "cmd-shim";
      packageName = "cmd-shim";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/cmd-shim/-/cmd-shim-2.0.2.tgz";
        sha1 = "6fcbda99483a8fd15d7d30a196ca69d688a2efdb";
      };
    };
    "columnify-1.5.4" = {
      name = "columnify";
      packageName = "columnify";
      version = "1.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/columnify/-/columnify-1.5.4.tgz";
        sha1 = "4737ddf1c7b69a8a7c340570782e947eec8e78bb";
      };
    };
    "config-chain-1.1.10" = {
      name = "config-chain";
      packageName = "config-chain";
      version = "1.1.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/config-chain/-/config-chain-1.1.10.tgz";
        sha1 = "7fc383de0fcc84d711cb465bd176579cad612346";
      };
    };
    "dezalgo-1.0.3" = {
      name = "dezalgo";
      packageName = "dezalgo";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dezalgo/-/dezalgo-1.0.3.tgz";
        sha1 = "7f742de066fc748bc8db820569dddce49bf0d456";
      };
    };
    "editor-1.0.0" = {
      name = "editor";
      packageName = "editor";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/editor/-/editor-1.0.0.tgz";
        sha1 = "60c7f87bd62bcc6a894fa8ccd6afb7823a24f742";
      };
    };
    "fs-vacuum-1.2.9" = {
      name = "fs-vacuum";
      packageName = "fs-vacuum";
      version = "1.2.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-vacuum/-/fs-vacuum-1.2.9.tgz";
        sha1 = "4f90193ab8ea02890995bcd4e804659a5d366b2d";
      };
    };
    "fs-write-stream-atomic-1.0.8" = {
      name = "fs-write-stream-atomic";
      packageName = "fs-write-stream-atomic";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs-write-stream-atomic/-/fs-write-stream-atomic-1.0.8.tgz";
        sha1 = "e49aaddf288f87d46ff9e882f216a13abc40778b";
      };
    };
    "fstream-1.0.10" = {
      name = "fstream";
      packageName = "fstream";
      version = "1.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream/-/fstream-1.0.10.tgz";
        sha1 = "604e8a92fe26ffd9f6fae30399d4984e1ab22822";
      };
    };
    "fstream-npm-1.0.7" = {
      name = "fstream-npm";
      packageName = "fstream-npm";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream-npm/-/fstream-npm-1.0.7.tgz";
        sha1 = "7ed0d1ac13d7686dd9e1bf6ceb8be273bf6d2f86";
      };
    };
    "github-url-from-git-1.4.0" = {
      name = "github-url-from-git";
      packageName = "github-url-from-git";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/github-url-from-git/-/github-url-from-git-1.4.0.tgz";
        sha1 = "285e6b520819001bde128674704379e4ff03e0de";
      };
    };
    "github-url-from-username-repo-1.0.2" = {
      name = "github-url-from-username-repo";
      packageName = "github-url-from-username-repo";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/github-url-from-username-repo/-/github-url-from-username-repo-1.0.2.tgz";
        sha1 = "7dd79330d2abe69c10c2cef79714c97215791dfa";
      };
    };
    "graceful-fs-4.1.9" = {
      name = "graceful-fs";
      packageName = "graceful-fs";
      version = "4.1.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-fs/-/graceful-fs-4.1.9.tgz";
        sha1 = "baacba37d19d11f9d146d3578bc99958c3787e29";
      };
    };
    "hosted-git-info-2.1.5" = {
      name = "hosted-git-info";
      packageName = "hosted-git-info";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/hosted-git-info/-/hosted-git-info-2.1.5.tgz";
        sha1 = "0ba81d90da2e25ab34a332e6ec77936e1598118b";
      };
    };
    "ini-1.3.4" = {
      name = "ini";
      packageName = "ini";
      version = "1.3.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/ini/-/ini-1.3.4.tgz";
        sha1 = "0537cb79daf59b59a1a517dff706c86ec039162e";
      };
    };
    "init-package-json-1.9.4" = {
      name = "init-package-json";
      packageName = "init-package-json";
      version = "1.9.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/init-package-json/-/init-package-json-1.9.4.tgz";
        sha1 = "b4053d0b40f0cf842a41966937cb3dc0f534e856";
      };
    };
    "lockfile-1.0.2" = {
      name = "lockfile";
      packageName = "lockfile";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lockfile/-/lockfile-1.0.2.tgz";
        sha1 = "97e1990174f696cbe0a3acd58a43b84aa30c7c83";
      };
    };
    "lru-cache-2.7.3" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "2.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-2.7.3.tgz";
        sha1 = "6d4524e8b955f95d4f5b58851ce21dd72fb4e952";
      };
    };
    "mkdirp-0.5.1" = {
      name = "mkdirp";
      packageName = "mkdirp";
      version = "0.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mkdirp/-/mkdirp-0.5.1.tgz";
        sha1 = "30057438eac6cf7f8c4767f38648d6697d75c903";
      };
    };
    "node-gyp-3.0.3" = {
      name = "node-gyp";
      packageName = "node-gyp";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-gyp/-/node-gyp-3.0.3.tgz";
        sha1 = "9b004219f4fa9efbfd78c5fc674aa12e58fb8694";
      };
    };
    "nopt-3.0.6" = {
      name = "nopt";
      packageName = "nopt";
      version = "3.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/nopt/-/nopt-3.0.6.tgz";
        sha1 = "c6465dbf08abcd4db359317f79ac68a646b28ff9";
      };
    };
    "normalize-git-url-3.0.2" = {
      name = "normalize-git-url";
      packageName = "normalize-git-url";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-git-url/-/normalize-git-url-3.0.2.tgz";
        sha1 = "8e5f14be0bdaedb73e07200310aa416c27350fc4";
      };
    };
    "normalize-package-data-2.3.5" = {
      name = "normalize-package-data";
      packageName = "normalize-package-data";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/normalize-package-data/-/normalize-package-data-2.3.5.tgz";
        sha1 = "8d924f142960e1777e7ffe170543631cc7cb02df";
      };
    };
    "npm-cache-filename-1.0.2" = {
      name = "npm-cache-filename";
      packageName = "npm-cache-filename";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-cache-filename/-/npm-cache-filename-1.0.2.tgz";
        sha1 = "ded306c5b0bfc870a9e9faf823bc5f283e05ae11";
      };
    };
    "npm-install-checks-1.0.7" = {
      name = "npm-install-checks";
      packageName = "npm-install-checks";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-install-checks/-/npm-install-checks-1.0.7.tgz";
        sha1 = "6d91aeda0ac96801f1ed7aadee116a6c0a086a57";
      };
    };
    "npm-package-arg-4.1.1" = {
      name = "npm-package-arg";
      packageName = "npm-package-arg";
      version = "4.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-package-arg/-/npm-package-arg-4.1.1.tgz";
        sha1 = "86d9dca985b4c5e5d59772dfd5de6919998a495a";
      };
    };
    "npm-registry-client-7.0.9" = {
      name = "npm-registry-client";
      packageName = "npm-registry-client";
      version = "7.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-registry-client/-/npm-registry-client-7.0.9.tgz";
        sha1 = "1baf86ee5285c4e6d38d4556208ded56049231bb";
      };
    };
    "npm-user-validate-0.1.5" = {
      name = "npm-user-validate";
      packageName = "npm-user-validate";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/npm-user-validate/-/npm-user-validate-0.1.5.tgz";
        sha1 = "52465d50c2d20294a57125b996baedbf56c5004b";
      };
    };
    "npmlog-2.0.4" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-2.0.4.tgz";
        sha1 = "98b52530f2514ca90d09ec5b22c8846722375692";
      };
    };
    "once-1.3.3" = {
      name = "once";
      packageName = "once";
      version = "1.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.3.3.tgz";
        sha1 = "b2e261557ce4c314ec8304f3fa82663e4297ca20";
      };
    };
    "opener-1.4.2" = {
      name = "opener";
      packageName = "opener";
      version = "1.4.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/opener/-/opener-1.4.2.tgz";
        sha1 = "b32582080042af8680c389a499175b4c54fff523";
      };
    };
    "osenv-0.1.3" = {
      name = "osenv";
      packageName = "osenv";
      version = "0.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/osenv/-/osenv-0.1.3.tgz";
        sha1 = "83cf05c6d6458fc4d5ac6362ea325d92f2754217";
      };
    };
    "path-is-inside-1.0.2" = {
      name = "path-is-inside";
      packageName = "path-is-inside";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-inside/-/path-is-inside-1.0.2.tgz";
        sha1 = "365417dede44430d1c11af61027facf074bdfc53";
      };
    };
    "read-1.0.7" = {
      name = "read";
      packageName = "read";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/read/-/read-1.0.7.tgz";
        sha1 = "b3da19bd052431a97671d44a42634adf710b40c4";
      };
    };
    "read-installed-4.0.3" = {
      name = "read-installed";
      packageName = "read-installed";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-installed/-/read-installed-4.0.3.tgz";
        sha1 = "ff9b8b67f187d1e4c29b9feb31f6b223acd19067";
      };
    };
    "read-package-json-2.0.4" = {
      name = "read-package-json";
      packageName = "read-package-json";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/read-package-json/-/read-package-json-2.0.4.tgz";
        sha1 = "61ed1b2256ea438d8008895090be84b8e799c853";
      };
    };
    "readable-stream-1.1.14" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "1.1.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-1.1.14.tgz";
        sha1 = "7cf4c54ef648e3813084c636dd2079e166c081d9";
      };
    };
    "realize-package-specifier-3.0.3" = {
      name = "realize-package-specifier";
      packageName = "realize-package-specifier";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/realize-package-specifier/-/realize-package-specifier-3.0.3.tgz";
        sha1 = "d0def882952b8de3f67eba5e91199661271f41f4";
      };
    };
    "request-2.65.0" = {
      name = "request";
      packageName = "request";
      version = "2.65.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request/-/request-2.65.0.tgz";
        sha1 = "cc1a3bc72b96254734fc34296da322f9486ddeba";
      };
    };
    "retry-0.8.0" = {
      name = "retry";
      packageName = "retry";
      version = "0.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/retry/-/retry-0.8.0.tgz";
        sha1 = "2367628dc0edb247b1eab649dc53ac8628ac2d5f";
      };
    };
    "rimraf-2.4.5" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.4.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.4.5.tgz";
        sha1 = "ee710ce5d93a8fdb856fb5ea8ff0e2d75934b2da";
      };
    };
    "semver-5.0.3" = {
      name = "semver";
      packageName = "semver";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.0.3.tgz";
        sha1 = "77466de589cd5d3c95f138aa78bc569a3cb5d27a";
      };
    };
    "sha-2.0.1" = {
      name = "sha";
      packageName = "sha";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sha/-/sha-2.0.1.tgz";
        sha1 = "6030822fbd2c9823949f8f72ed6411ee5cf25aae";
      };
    };
    "slide-1.1.6" = {
      name = "slide";
      packageName = "slide";
      version = "1.1.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/slide/-/slide-1.1.6.tgz";
        sha1 = "56eb027d65b4d2dce6cb2e2d32c4d4afc9e1d707";
      };
    };
    "sorted-object-1.0.0" = {
      name = "sorted-object";
      packageName = "sorted-object";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/sorted-object/-/sorted-object-1.0.0.tgz";
        sha1 = "5d1f4f9c1fb2cd48965967304e212eb44cfb6d05";
      };
    };
    "spdx-0.4.3" = {
      name = "spdx";
      packageName = "spdx";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx/-/spdx-0.4.3.tgz";
        sha1 = "ab373c3fcf7b84ffd8fdeb0592d24ff0d14812e4";
      };
    };
    "tar-2.2.1" = {
      name = "tar";
      packageName = "tar";
      version = "2.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-2.2.1.tgz";
        sha1 = "8e4d2a256c0e2185c6b18ad694aec968b83cb1d1";
      };
    };
    "text-table-0.2.0" = {
      name = "text-table";
      packageName = "text-table";
      version = "0.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/text-table/-/text-table-0.2.0.tgz";
        sha1 = "7f5ee823ae805207c00af2df4a84ec3fcfa570b4";
      };
    };
    "uid-number-0.0.6" = {
      name = "uid-number";
      packageName = "uid-number";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/uid-number/-/uid-number-0.0.6.tgz";
        sha1 = "0ea10e8035e8eb5b8e4449f06da1c730663baa81";
      };
    };
    "umask-1.1.0" = {
      name = "umask";
      packageName = "umask";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/umask/-/umask-1.1.0.tgz";
        sha1 = "f29cebf01df517912bb58ff9c4e50fde8e33320d";
      };
    };
    "validate-npm-package-license-3.0.1" = {
      name = "validate-npm-package-license";
      packageName = "validate-npm-package-license";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-license/-/validate-npm-package-license-3.0.1.tgz";
        sha1 = "2804babe712ad3379459acfbe24746ab2c303fbc";
      };
    };
    "validate-npm-package-name-2.2.2" = {
      name = "validate-npm-package-name";
      packageName = "validate-npm-package-name";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/validate-npm-package-name/-/validate-npm-package-name-2.2.2.tgz";
        sha1 = "f65695b22f7324442019a3c7fa39a6e7fd299085";
      };
    };
    "which-1.2.11" = {
      name = "which";
      packageName = "which";
      version = "1.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/which/-/which-1.2.11.tgz";
        sha1 = "c8b2eeea6b8c1659fa7c1dd4fdaabe9533dc5e8b";
      };
    };
    "write-file-atomic-1.1.4" = {
      name = "write-file-atomic";
      packageName = "write-file-atomic";
      version = "1.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/write-file-atomic/-/write-file-atomic-1.1.4.tgz";
        sha1 = "b1f52dc2e8dc0e3cb04d187a25f758a38a90ca3b";
      };
    };
    "spdx-license-ids-1.2.2" = {
      name = "spdx-license-ids";
      packageName = "spdx-license-ids";
      version = "1.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-license-ids/-/spdx-license-ids-1.2.2.tgz";
        sha1 = "c9df7a3424594ade6bd11900d596696dc06bac57";
      };
    };
    "wcwidth-1.0.1" = {
      name = "wcwidth";
      packageName = "wcwidth";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/wcwidth/-/wcwidth-1.0.1.tgz";
        sha1 = "f0b0dcf915bc5ff1528afadb2c0e17b532da2fe8";
      };
    };
    "defaults-1.0.3" = {
      name = "defaults";
      packageName = "defaults";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/defaults/-/defaults-1.0.3.tgz";
        sha1 = "c656051e9817d9ff08ed881477f3fe4019f3ef7d";
      };
    };
    "clone-1.0.2" = {
      name = "clone";
      packageName = "clone";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/clone/-/clone-1.0.2.tgz";
        sha1 = "260b7a99ebb1edfe247538175f783243cb19d149";
      };
    };
    "proto-list-1.2.4" = {
      name = "proto-list";
      packageName = "proto-list";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/proto-list/-/proto-list-1.2.4.tgz";
        sha1 = "212d5bfe1318306a420f6402b8e26ff39647a849";
      };
    };
    "asap-2.0.5" = {
      name = "asap";
      packageName = "asap";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/asap/-/asap-2.0.5.tgz";
        sha1 = "522765b50c3510490e52d7dcfe085ef9ba96958f";
      };
    };
    "rimraf-2.5.4" = {
      name = "rimraf";
      packageName = "rimraf";
      version = "2.5.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/rimraf/-/rimraf-2.5.4.tgz";
        sha1 = "96800093cbf1a0c86bd95b4625467535c29dfa04";
      };
    };
    "glob-7.1.0" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.0.tgz";
        sha1 = "36add856d746d0d99e4cc2797bba1ae2c67272fd";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "iferr-0.1.5" = {
      name = "iferr";
      packageName = "iferr";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/iferr/-/iferr-0.1.5.tgz";
        sha1 = "c60eed69e6d8fdb6b3104a1fcbca1c192dc5b501";
      };
    };
    "imurmurhash-0.1.4" = {
      name = "imurmurhash";
      packageName = "imurmurhash";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/imurmurhash/-/imurmurhash-0.1.4.tgz";
        sha1 = "9218b9b2b928a238b13dc4fb6b6d576f231453ea";
      };
    };
    "fstream-ignore-1.0.5" = {
      name = "fstream-ignore";
      packageName = "fstream-ignore";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/fstream-ignore/-/fstream-ignore-1.0.5.tgz";
        sha1 = "9c31dae34767018fe1d249b24dada67d092da105";
      };
    };
    "glob-6.0.4" = {
      name = "glob";
      packageName = "glob";
      version = "6.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-6.0.4.tgz";
        sha1 = "0f08860f6a155127b2fadd4f9ce24b1aab6e4d22";
      };
    };
    "promzard-0.3.0" = {
      name = "promzard";
      packageName = "promzard";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/promzard/-/promzard-0.3.0.tgz";
        sha1 = "26a5d6ee8c7dee4cb12208305acfb93ba382a9ee";
      };
    };
    "minimist-0.0.8" = {
      name = "minimist";
      packageName = "minimist";
      version = "0.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz";
        sha1 = "857fcabfc3397d2625b8228262e86aa7a011b05d";
      };
    };
    "glob-4.5.3" = {
      name = "glob";
      packageName = "glob";
      version = "4.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-4.5.3.tgz";
        sha1 = "c6cb73d3226c1efef04de3c56d012f03377ee15f";
      };
    };
    "minimatch-1.0.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-1.0.0.tgz";
        sha1 = "e0dd2120b49e1b724ce8d714c520822a9438576d";
      };
    };
    "npmlog-1.2.1" = {
      name = "npmlog";
      packageName = "npmlog";
      version = "1.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/npmlog/-/npmlog-1.2.1.tgz";
        sha1 = "28e7be619609b53f7ad1dd300a10d64d716268b6";
      };
    };
    "path-array-1.0.1" = {
      name = "path-array";
      packageName = "path-array";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-array/-/path-array-1.0.1.tgz";
        sha1 = "7e2f0f35f07a2015122b868b7eac0eb2c4fec271";
      };
    };
    "tar-1.0.3" = {
      name = "tar";
      packageName = "tar";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tar/-/tar-1.0.3.tgz";
        sha1 = "15bcdab244fa4add44e4244a0176edb8aa9a2b44";
      };
    };
    "minimatch-2.0.10" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "2.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-2.0.10.tgz";
        sha1 = "8d087c39c6b38c001b97fca7ce6d0e1e80afbac7";
      };
    };
    "sigmund-1.0.1" = {
      name = "sigmund";
      packageName = "sigmund";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/sigmund/-/sigmund-1.0.1.tgz";
        sha1 = "3ff21f198cad2175f9f3b781853fd94d0d19b590";
      };
    };
    "are-we-there-yet-1.0.6" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.0.6.tgz";
        sha1 = "a2d28c93102aa6cc96245a26cb954de06ec53f0c";
      };
    };
    "gauge-1.2.7" = {
      name = "gauge";
      packageName = "gauge";
      version = "1.2.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/gauge/-/gauge-1.2.7.tgz";
        sha1 = "e9cec5483d3d4ee0ef44b60a7d99e4935e136d93";
      };
    };
    "delegates-1.0.0" = {
      name = "delegates";
      packageName = "delegates";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delegates/-/delegates-1.0.0.tgz";
        sha1 = "84c6e159b81904fdca59a0ef44cd870d31250f9a";
      };
    };
    "has-unicode-2.0.1" = {
      name = "has-unicode";
      packageName = "has-unicode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/has-unicode/-/has-unicode-2.0.1.tgz";
        sha1 = "e0e6fe6a28cf51138855e086d1691e771de2a8b9";
      };
    };
    "lodash.pad-4.5.1" = {
      name = "lodash.pad";
      packageName = "lodash.pad";
      version = "4.5.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.pad/-/lodash.pad-4.5.1.tgz";
        sha1 = "4330949a833a7c8da22cc20f6a26c4d59debba70";
      };
    };
    "lodash.padend-4.6.1" = {
      name = "lodash.padend";
      packageName = "lodash.padend";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.padend/-/lodash.padend-4.6.1.tgz";
        sha1 = "53ccba047d06e158d311f45da625f4e49e6f166e";
      };
    };
    "lodash.padstart-4.6.1" = {
      name = "lodash.padstart";
      packageName = "lodash.padstart";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.padstart/-/lodash.padstart-4.6.1.tgz";
        sha1 = "d2e3eebff0d9d39ad50f5cbd1b52a7bce6bb611b";
      };
    };
    "array-index-1.0.0" = {
      name = "array-index";
      packageName = "array-index";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/array-index/-/array-index-1.0.0.tgz";
        sha1 = "ec56a749ee103e4e08c790b9c353df16055b97f9";
      };
    };
    "es6-symbol-3.1.0" = {
      name = "es6-symbol";
      packageName = "es6-symbol";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-symbol/-/es6-symbol-3.1.0.tgz";
        sha1 = "94481c655e7a7cad82eba832d97d5433496d7ffa";
      };
    };
    "d-0.1.1" = {
      name = "d";
      packageName = "d";
      version = "0.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/d/-/d-0.1.1.tgz";
        sha1 = "da184c535d18d8ee7ba2aa229b914009fae11309";
      };
    };
    "es5-ext-0.10.12" = {
      name = "es5-ext";
      packageName = "es5-ext";
      version = "0.10.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/es5-ext/-/es5-ext-0.10.12.tgz";
        sha1 = "aa84641d4db76b62abba5e45fd805ecbab140047";
      };
    };
    "es6-iterator-2.0.0" = {
      name = "es6-iterator";
      packageName = "es6-iterator";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/es6-iterator/-/es6-iterator-2.0.0.tgz";
        sha1 = "bd968567d61635e33c0b80727613c9cb4b096bac";
      };
    };
    "is-builtin-module-1.0.0" = {
      name = "is-builtin-module";
      packageName = "is-builtin-module";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-builtin-module/-/is-builtin-module-1.0.0.tgz";
        sha1 = "540572d34f7ac3119f8f76c30cbc1b1e037affbe";
      };
    };
    "builtin-modules-1.1.1" = {
      name = "builtin-modules";
      packageName = "builtin-modules";
      version = "1.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtin-modules/-/builtin-modules-1.1.1.tgz";
        sha1 = "270f076c5a72c02f5b65a47df94c5fe3a278892f";
      };
    };
    "concat-stream-1.5.2" = {
      name = "concat-stream";
      packageName = "concat-stream";
      version = "1.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-stream/-/concat-stream-1.5.2.tgz";
        sha1 = "708978624d856af41a5a741defdd261da752c266";
      };
    };
    "typedarray-0.0.6" = {
      name = "typedarray";
      packageName = "typedarray";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typedarray/-/typedarray-0.0.6.tgz";
        sha1 = "867ac74e3864187b1d3d47d996a78ec5c8830777";
      };
    };
    "readable-stream-2.0.6" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.0.6.tgz";
        sha1 = "8f90341e68a53ccc928788dacfcd11b36eb9b78e";
      };
    };
    "core-util-is-1.0.2" = {
      name = "core-util-is";
      packageName = "core-util-is";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-util-is/-/core-util-is-1.0.2.tgz";
        sha1 = "b5fd54220aa2bc5ab57aab7140c940754503c1a7";
      };
    };
    "isarray-1.0.0" = {
      name = "isarray";
      packageName = "isarray";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-1.0.0.tgz";
        sha1 = "bb935d48582cba168c06834957a54a3e07124f11";
      };
    };
    "process-nextick-args-1.0.7" = {
      name = "process-nextick-args";
      packageName = "process-nextick-args";
      version = "1.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/process-nextick-args/-/process-nextick-args-1.0.7.tgz";
        sha1 = "150e20b756590ad3f91093f25a4f2ad8bff30ba3";
      };
    };
    "string_decoder-0.10.31" = {
      name = "string_decoder";
      packageName = "string_decoder";
      version = "0.10.31";
      src = fetchurl {
        url = "https://registry.npmjs.org/string_decoder/-/string_decoder-0.10.31.tgz";
        sha1 = "62e203bc41766c6c28c9fc84301dab1c5310fa94";
      };
    };
    "util-deprecate-1.0.2" = {
      name = "util-deprecate";
      packageName = "util-deprecate";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-deprecate/-/util-deprecate-1.0.2.tgz";
        sha1 = "450d4dc9fa70de732762fbd2d4a28981419a0ccf";
      };
    };
    "are-we-there-yet-1.1.2" = {
      name = "are-we-there-yet";
      packageName = "are-we-there-yet";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/are-we-there-yet/-/are-we-there-yet-1.1.2.tgz";
        sha1 = "80e470e95a084794fe1899262c5667c6e88de1b3";
      };
    };
    "os-homedir-1.0.2" = {
      name = "os-homedir";
      packageName = "os-homedir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-homedir/-/os-homedir-1.0.2.tgz";
        sha1 = "ffbc4988336e0e833de0c168c7ef152121aa7fb3";
      };
    };
    "os-tmpdir-1.0.2" = {
      name = "os-tmpdir";
      packageName = "os-tmpdir";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/os-tmpdir/-/os-tmpdir-1.0.2.tgz";
        sha1 = "bbe67406c79aa85c5cfec766fe5734555dfa1274";
      };
    };
    "mute-stream-0.0.6" = {
      name = "mute-stream";
      packageName = "mute-stream";
      version = "0.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/mute-stream/-/mute-stream-0.0.6.tgz";
        sha1 = "48962b19e169fd1dfc240b3f1e7317627bbc47db";
      };
    };
    "debuglog-1.0.1" = {
      name = "debuglog";
      packageName = "debuglog";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/debuglog/-/debuglog-1.0.1.tgz";
        sha1 = "aa24ffb9ac3df9a2351837cfb2d279360cd78492";
      };
    };
    "readdir-scoped-modules-1.0.2" = {
      name = "readdir-scoped-modules";
      packageName = "readdir-scoped-modules";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/readdir-scoped-modules/-/readdir-scoped-modules-1.0.2.tgz";
        sha1 = "9fafa37d286be5d92cbaebdee030dc9b5f406747";
      };
    };
    "util-extend-1.0.3" = {
      name = "util-extend";
      packageName = "util-extend";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/util-extend/-/util-extend-1.0.3.tgz";
        sha1 = "a7c216d267545169637b3b6edc6ca9119e2ff93f";
      };
    };
    "json-parse-helpfulerror-1.0.3" = {
      name = "json-parse-helpfulerror";
      packageName = "json-parse-helpfulerror";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-parse-helpfulerror/-/json-parse-helpfulerror-1.0.3.tgz";
        sha1 = "13f14ce02eed4e981297b64eb9e3b932e2dd13dc";
      };
    };
    "jju-1.3.0" = {
      name = "jju";
      packageName = "jju";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jju/-/jju-1.3.0.tgz";
        sha1 = "dadd9ef01924bc728b03f2f7979bdbd62f7a2aaa";
      };
    };
    "isarray-0.0.1" = {
      name = "isarray";
      packageName = "isarray";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/isarray/-/isarray-0.0.1.tgz";
        sha1 = "8a18acfca9a8f4177e09abfc6038939b05d1eedf";
      };
    };
    "bl-1.0.3" = {
      name = "bl";
      packageName = "bl";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/bl/-/bl-1.0.3.tgz";
        sha1 = "fc5421a28fd4226036c3b3891a66a25bc64d226e";
      };
    };
    "caseless-0.11.0" = {
      name = "caseless";
      packageName = "caseless";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/caseless/-/caseless-0.11.0.tgz";
        sha1 = "715b96ea9841593cc33067923f5ec60ebda4f7d7";
      };
    };
    "extend-3.0.0" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.0.tgz";
        sha1 = "5a474353b9f3353ddd8176dfd37b91c83a46f1d4";
      };
    };
    "forever-agent-0.6.1" = {
      name = "forever-agent";
      packageName = "forever-agent";
      version = "0.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/forever-agent/-/forever-agent-0.6.1.tgz";
        sha1 = "fbc71f0c41adeb37f96c577ad1ed42d8fdacca91";
      };
    };
    "form-data-1.0.1" = {
      name = "form-data";
      packageName = "form-data";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/form-data/-/form-data-1.0.1.tgz";
        sha1 = "ae315db9a4907fa065502304a66d7733475ee37c";
      };
    };
    "json-stringify-safe-5.0.1" = {
      name = "json-stringify-safe";
      packageName = "json-stringify-safe";
      version = "5.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-stringify-safe/-/json-stringify-safe-5.0.1.tgz";
        sha1 = "1296a2d58fd45f19a0f6ce01d65701e2c735b6eb";
      };
    };
    "mime-types-2.1.12" = {
      name = "mime-types";
      packageName = "mime-types";
      version = "2.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-types/-/mime-types-2.1.12.tgz";
        sha1 = "152ba256777020dd4663f54c2e7bc26381e71729";
      };
    };
    "node-uuid-1.4.7" = {
      name = "node-uuid";
      packageName = "node-uuid";
      version = "1.4.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-uuid/-/node-uuid-1.4.7.tgz";
        sha1 = "6da5a17668c4b3dd59623bda11cf7fa4c1f60a6f";
      };
    };
    "qs-5.2.1" = {
      name = "qs";
      packageName = "qs";
      version = "5.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/qs/-/qs-5.2.1.tgz";
        sha1 = "801fee030e0b9450d6385adc48a4cc55b44aedfc";
      };
    };
    "tunnel-agent-0.4.3" = {
      name = "tunnel-agent";
      packageName = "tunnel-agent";
      version = "0.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tunnel-agent/-/tunnel-agent-0.4.3.tgz";
        sha1 = "6373db76909fe570e08d73583365ed828a74eeeb";
      };
    };
    "tough-cookie-2.2.2" = {
      name = "tough-cookie";
      packageName = "tough-cookie";
      version = "2.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/tough-cookie/-/tough-cookie-2.2.2.tgz";
        sha1 = "c83a1830f4e5ef0b93ef2a3488e724f8de016ac7";
      };
    };
    "http-signature-0.11.0" = {
      name = "http-signature";
      packageName = "http-signature";
      version = "0.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/http-signature/-/http-signature-0.11.0.tgz";
        sha1 = "1796cf67a001ad5cd6849dca0991485f09089fe6";
      };
    };
    "oauth-sign-0.8.2" = {
      name = "oauth-sign";
      packageName = "oauth-sign";
      version = "0.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/oauth-sign/-/oauth-sign-0.8.2.tgz";
        sha1 = "46a6ab7f0aead8deae9ec0565780b7d4efeb9d43";
      };
    };
    "hawk-3.1.3" = {
      name = "hawk";
      packageName = "hawk";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hawk/-/hawk-3.1.3.tgz";
        sha1 = "078444bd7c1640b0fe540d2c9b73d59678e8e1c4";
      };
    };
    "aws-sign2-0.6.0" = {
      name = "aws-sign2";
      packageName = "aws-sign2";
      version = "0.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aws-sign2/-/aws-sign2-0.6.0.tgz";
        sha1 = "14342dd38dbcc94d0e5b87d763cd63612c0e794f";
      };
    };
    "stringstream-0.0.5" = {
      name = "stringstream";
      packageName = "stringstream";
      version = "0.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringstream/-/stringstream-0.0.5.tgz";
        sha1 = "4e484cd4de5a0bbbee18e46307710a8a81621878";
      };
    };
    "combined-stream-1.0.5" = {
      name = "combined-stream";
      packageName = "combined-stream";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/combined-stream/-/combined-stream-1.0.5.tgz";
        sha1 = "938370a57b4a51dea2c77c15d5c5fdf895164009";
      };
    };
    "isstream-0.1.2" = {
      name = "isstream";
      packageName = "isstream";
      version = "0.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isstream/-/isstream-0.1.2.tgz";
        sha1 = "47e63f7af55afa6f92e1500e690eb8b8529c099a";
      };
    };
    "har-validator-2.0.6" = {
      name = "har-validator";
      packageName = "har-validator";
      version = "2.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/har-validator/-/har-validator-2.0.6.tgz";
        sha1 = "cdcbc08188265ad119b6a5a7c8ab70eecfb5d27d";
      };
    };
    "async-2.0.1" = {
      name = "async";
      packageName = "async";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/async/-/async-2.0.1.tgz";
        sha1 = "b709cc0280a9c36f09f4536be823c838a9049e25";
      };
    };
    "lodash-4.16.2" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.16.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.16.2.tgz";
        sha1 = "3e626db827048a699281a8a125226326cfc0e652";
      };
    };
    "mime-db-1.24.0" = {
      name = "mime-db";
      packageName = "mime-db";
      version = "1.24.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mime-db/-/mime-db-1.24.0.tgz";
        sha1 = "e2d13f939f0016c6e4e9ad25a8652f126c467f0c";
      };
    };
    "assert-plus-0.1.5" = {
      name = "assert-plus";
      packageName = "assert-plus";
      version = "0.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/assert-plus/-/assert-plus-0.1.5.tgz";
        sha1 = "ee74009413002d84cec7219c6ac811812e723160";
      };
    };
    "asn1-0.1.11" = {
      name = "asn1";
      packageName = "asn1";
      version = "0.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/asn1/-/asn1-0.1.11.tgz";
        sha1 = "559be18376d08a4ec4dbe80877d27818639b2df7";
      };
    };
    "ctype-0.5.3" = {
      name = "ctype";
      packageName = "ctype";
      version = "0.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ctype/-/ctype-0.5.3.tgz";
        sha1 = "82c18c2461f74114ef16c135224ad0b9144ca12f";
      };
    };
    "hoek-2.16.3" = {
      name = "hoek";
      packageName = "hoek";
      version = "2.16.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/hoek/-/hoek-2.16.3.tgz";
        sha1 = "20bb7403d3cea398e91dc4710a8ff1b8274a25ed";
      };
    };
    "boom-2.10.1" = {
      name = "boom";
      packageName = "boom";
      version = "2.10.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/boom/-/boom-2.10.1.tgz";
        sha1 = "39c8918ceff5799f83f9492a848f625add0c766f";
      };
    };
    "cryptiles-2.0.5" = {
      name = "cryptiles";
      packageName = "cryptiles";
      version = "2.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/cryptiles/-/cryptiles-2.0.5.tgz";
        sha1 = "3bdfecdc608147c1c67202fa291e7dca59eaa3b8";
      };
    };
    "sntp-1.0.9" = {
      name = "sntp";
      packageName = "sntp";
      version = "1.0.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sntp/-/sntp-1.0.9.tgz";
        sha1 = "6541184cc90aeea6c6e7b35e2659082443c66198";
      };
    };
    "delayed-stream-1.0.0" = {
      name = "delayed-stream";
      packageName = "delayed-stream";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/delayed-stream/-/delayed-stream-1.0.0.tgz";
        sha1 = "df3ae199acadfb7d440aaae0b29e2272b24ec619";
      };
    };
    "commander-2.9.0" = {
      name = "commander";
      packageName = "commander";
      version = "2.9.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-2.9.0.tgz";
        sha1 = "9c99094176e12240cb22d6c5146098400fe0f7d4";
      };
    };
    "is-my-json-valid-2.14.0" = {
      name = "is-my-json-valid";
      packageName = "is-my-json-valid";
      version = "2.14.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-my-json-valid/-/is-my-json-valid-2.14.0.tgz";
        sha1 = "47bf808609b2df5d48c969c74becd09fbca02725";
      };
    };
    "pinkie-promise-2.0.1" = {
      name = "pinkie-promise";
      packageName = "pinkie-promise";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie-promise/-/pinkie-promise-2.0.1.tgz";
        sha1 = "2135d6dfa7a358c069ac9b178776288228450ffa";
      };
    };
    "graceful-readlink-1.0.1" = {
      name = "graceful-readlink";
      packageName = "graceful-readlink";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/graceful-readlink/-/graceful-readlink-1.0.1.tgz";
        sha1 = "4cafad76bc62f02fa039b2f94e9a3dd3a391a725";
      };
    };
    "generate-function-2.0.0" = {
      name = "generate-function";
      packageName = "generate-function";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-function/-/generate-function-2.0.0.tgz";
        sha1 = "6858fe7c0969b7d4e9093337647ac79f60dfbe74";
      };
    };
    "generate-object-property-1.2.0" = {
      name = "generate-object-property";
      packageName = "generate-object-property";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/generate-object-property/-/generate-object-property-1.2.0.tgz";
        sha1 = "9c0e1c40308ce804f4783618b937fa88f99d50d0";
      };
    };
    "jsonpointer-2.0.0" = {
      name = "jsonpointer";
      packageName = "jsonpointer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonpointer/-/jsonpointer-2.0.0.tgz";
        sha1 = "3af1dd20fe85463910d469a385e33017d2a030d9";
      };
    };
    "is-property-1.0.2" = {
      name = "is-property";
      packageName = "is-property";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-property/-/is-property-1.0.2.tgz";
        sha1 = "57fe1c4e48474edd65b09911f26b1cd4095dda84";
      };
    };
    "pinkie-2.0.4" = {
      name = "pinkie";
      packageName = "pinkie";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/pinkie/-/pinkie-2.0.4.tgz";
        sha1 = "72556b80cfa0d48a974e80e77248e80ed4f7f870";
      };
    };
    "readable-stream-2.1.5" = {
      name = "readable-stream";
      packageName = "readable-stream";
      version = "2.1.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/readable-stream/-/readable-stream-2.1.5.tgz";
        sha1 = "66fa8b720e1438b364681f2ad1a63c618448c9d0";
      };
    };
    "buffer-shims-1.0.0" = {
      name = "buffer-shims";
      packageName = "buffer-shims";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/buffer-shims/-/buffer-shims-1.0.0.tgz";
        sha1 = "9978ce317388c649ad8793028c3477ef044a8b51";
      };
    };
    "spdx-correct-1.0.2" = {
      name = "spdx-correct";
      packageName = "spdx-correct";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-correct/-/spdx-correct-1.0.2.tgz";
        sha1 = "4b3073d933ff51f3912f03ac5519498a4150db40";
      };
    };
    "spdx-expression-parse-1.0.3" = {
      name = "spdx-expression-parse";
      packageName = "spdx-expression-parse";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/spdx-expression-parse/-/spdx-expression-parse-1.0.3.tgz";
        sha1 = "ca3c3828c4fea8aa44997884b398fc5d67436442";
      };
    };
    "builtins-0.0.7" = {
      name = "builtins";
      packageName = "builtins";
      version = "0.0.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/builtins/-/builtins-0.0.7.tgz";
        sha1 = "355219cd6cf18dbe7c01cc7fd2dce765cfdc549a";
      };
    };
    "isexe-1.1.2" = {
      name = "isexe";
      packageName = "isexe";
      version = "1.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/isexe/-/isexe-1.1.2.tgz";
        sha1 = "36f3e22e60750920f5e7241a476a8c6a42275ad0";
      };
    };
    "semver-5.3.0" = {
      name = "semver";
      packageName = "semver";
      version = "5.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-5.3.0.tgz";
        sha1 = "9b2ce5d3de02d17c6012ad326aa6b4d0cf54f94f";
      };
    };
    "ramda-0.17.1" = {
      name = "ramda";
      packageName = "ramda";
      version = "0.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ramda/-/ramda-0.17.1.tgz";
        sha1 = "4c198147d3ab54e8c15255f11730e2116f6e6073";
      };
    };
    "acorn-3.3.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "3.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-3.3.0.tgz";
        sha1 = "45e37fb39e8da3f25baee3ff5369e2bb5f22017a";
      };
    };
    "enhanced-resolve-2.3.0" = {
      name = "enhanced-resolve";
      packageName = "enhanced-resolve";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/enhanced-resolve/-/enhanced-resolve-2.3.0.tgz";
        sha1 = "a115c32504b6302e85a76269d7a57ccdd962e359";
      };
    };
    "glob-3.2.11" = {
      name = "glob";
      packageName = "glob";
      version = "3.2.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-3.2.11.tgz";
        sha1 = "4a973f635b9190f715d10987d5c00fd2815ebe3d";
      };
    };
    "minimatch-0.2.14" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.2.14";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.2.14.tgz";
        sha1 = "c74e780574f63c6f9a090e90efbe6ef53a6a756a";
      };
    };
    "resolve-from-2.0.0" = {
      name = "resolve-from";
      packageName = "resolve-from";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/resolve-from/-/resolve-from-2.0.0.tgz";
        sha1 = "9480ab20e94ffa1d9e80a804c7ea147611966b57";
      };
    };
    "tapable-0.2.4" = {
      name = "tapable";
      packageName = "tapable";
      version = "0.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/tapable/-/tapable-0.2.4.tgz";
        sha1 = "a7814605089d4ba896c33c7e3566e13dcd194aa5";
      };
    };
    "memory-fs-0.3.0" = {
      name = "memory-fs";
      packageName = "memory-fs";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/memory-fs/-/memory-fs-0.3.0.tgz";
        sha1 = "7bcc6b629e3a43e871d7e29aca6ae8a7f15cbb20";
      };
    };
    "object-assign-4.1.0" = {
      name = "object-assign";
      packageName = "object-assign";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/object-assign/-/object-assign-4.1.0.tgz";
        sha1 = "7a3b3d0e98063d43f4c03f2e8ae6cd51a86883a0";
      };
    };
    "errno-0.1.4" = {
      name = "errno";
      packageName = "errno";
      version = "0.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/errno/-/errno-0.1.4.tgz";
        sha1 = "b896e23a9e5e8ba33871fc996abd3635fc9a1c7d";
      };
    };
    "prr-0.0.0" = {
      name = "prr";
      packageName = "prr";
      version = "0.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prr/-/prr-0.0.0.tgz";
        sha1 = "1a84b85908325501411853d0081ee3fa86e2926a";
      };
    };
    "minimatch-0.3.0" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-0.3.0.tgz";
        sha1 = "275d8edaac4f1bb3326472089e7949c8394699dd";
      };
    };
  };
in
{
  jsonlint = nodeEnv.buildNodePackage {
    name = "jsonlint";
    packageName = "jsonlint";
    version = "1.6.2";
    src = fetchurl {
      url = "https://registry.npmjs.org/jsonlint/-/jsonlint-1.6.2.tgz";
      sha1 = "5737045085f55eb455c68b1ff4ebc01bd50e8830";
    };
    dependencies = [
      sources."nomnom-1.8.1"
      sources."JSV-4.0.2"
      sources."underscore-1.6.0"
      sources."chalk-0.4.0"
      sources."has-color-0.1.7"
      sources."ansi-styles-1.0.0"
      sources."strip-ansi-0.1.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Validate JSON";
      homepage = http://zaach.github.com/jsonlint/;
    };
    production = true;
  };
  replem = nodeEnv.buildNodePackage {
    name = "replem";
    packageName = "replem";
    version = "1.10.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/replem/-/replem-1.10.5.tgz";
      sha1 = "cc8450ced0975d2dd394921c1194b9b10beb300d";
    };
    dependencies = [
      sources."camelcase-1.2.1"
      sources."chalk-1.1.3"
      sources."char-spinner-1.0.1"
      sources."debug-2.2.0"
      sources."glob-5.0.15"
      sources."minimist-1.2.0"
      (sources."npm-2.14.11" // {
        dependencies = [
          sources."npm-package-arg-4.1.1"
          sources."once-1.3.3"
        ];
      })
      (sources."npm-package-arg-4.2.0" // {
        dependencies = [
          sources."semver-5.3.0"
        ];
      })
      sources."ramda-0.18.0"
      (sources."ramda-fantasy-0.4.1" // {
        dependencies = [
          sources."ramda-0.17.1"
        ];
      })
      sources."repl.history-0.1.3"
      (sources."sanctuary-0.7.1" // {
        dependencies = [
          sources."ramda-0.17.1"
        ];
      })
      sources."xtend-4.0.1"
      sources."ansi-styles-2.2.1"
      sources."escape-string-regexp-1.0.5"
      sources."has-ansi-2.0.0"
      sources."strip-ansi-3.0.1"
      sources."supports-color-2.0.0"
      sources."ansi-regex-2.0.0"
      sources."ms-0.7.1"
      sources."inflight-1.0.5"
      sources."inherits-2.0.3"
      sources."minimatch-3.0.3"
      sources."once-1.4.0"
      sources."path-is-absolute-1.0.1"
      sources."wrappy-1.0.2"
      sources."brace-expansion-1.1.6"
      sources."balanced-match-0.4.2"
      sources."concat-map-0.0.1"
      sources."abbrev-1.0.9"
      sources."ansi-0.3.1"
      sources."ansicolors-0.3.2"
      sources."ansistyles-0.1.3"
      sources."archy-1.0.0"
      sources."async-some-1.0.2"
      sources."block-stream-0.0.8"
      sources."chmodr-1.0.2"
      sources."chownr-1.0.1"
      sources."cmd-shim-2.0.2"
      sources."columnify-1.5.4"
      sources."config-chain-1.1.10"
      sources."dezalgo-1.0.3"
      sources."editor-1.0.0"
      (sources."fs-vacuum-1.2.9" // {
        dependencies = [
          sources."rimraf-2.5.4"
          sources."glob-7.1.0"
        ];
      })
      sources."fs-write-stream-atomic-1.0.8"
      sources."fstream-1.0.10"
      sources."fstream-npm-1.0.7"
      sources."github-url-from-git-1.4.0"
      sources."github-url-from-username-repo-1.0.2"
      sources."graceful-fs-4.1.9"
      sources."hosted-git-info-2.1.5"
      sources."ini-1.3.4"
      (sources."init-package-json-1.9.4" // {
        dependencies = [
          sources."glob-6.0.4"
        ];
      })
      sources."lockfile-1.0.2"
      sources."lru-cache-2.7.3"
      (sources."mkdirp-0.5.1" // {
        dependencies = [
          sources."minimist-0.0.8"
        ];
      })
      (sources."node-gyp-3.0.3" // {
        dependencies = [
          (sources."glob-4.5.3" // {
            dependencies = [
              sources."minimatch-2.0.10"
            ];
          })
          sources."minimatch-1.0.0"
          sources."npmlog-1.2.1"
          sources."tar-1.0.3"
        ];
      })
      sources."nopt-3.0.6"
      sources."normalize-git-url-3.0.2"
      sources."normalize-package-data-2.3.5"
      sources."npm-cache-filename-1.0.2"
      sources."npm-install-checks-1.0.7"
      sources."npm-registry-client-7.0.9"
      sources."npm-user-validate-0.1.5"
      (sources."npmlog-2.0.4" // {
        dependencies = [
          sources."are-we-there-yet-1.1.2"
        ];
      })
      sources."opener-1.4.2"
      sources."osenv-0.1.3"
      sources."path-is-inside-1.0.2"
      sources."read-1.0.7"
      sources."read-installed-4.0.3"
      (sources."read-package-json-2.0.4" // {
        dependencies = [
          sources."glob-6.0.4"
        ];
      })
      (sources."readable-stream-1.1.14" // {
        dependencies = [
          sources."isarray-0.0.1"
        ];
      })
      sources."realize-package-specifier-3.0.3"
      sources."request-2.65.0"
      sources."retry-0.8.0"
      (sources."rimraf-2.4.5" // {
        dependencies = [
          sources."glob-6.0.4"
        ];
      })
      sources."semver-5.0.3"
      (sources."sha-2.0.1" // {
        dependencies = [
          sources."readable-stream-2.1.5"
        ];
      })
      sources."slide-1.1.6"
      sources."sorted-object-1.0.0"
      sources."spdx-0.4.3"
      sources."tar-2.2.1"
      sources."text-table-0.2.0"
      sources."uid-number-0.0.6"
      sources."umask-1.1.0"
      sources."validate-npm-package-license-3.0.1"
      sources."validate-npm-package-name-2.2.2"
      sources."which-1.2.11"
      sources."write-file-atomic-1.1.4"
      sources."spdx-license-ids-1.2.2"
      sources."wcwidth-1.0.1"
      sources."defaults-1.0.3"
      sources."clone-1.0.2"
      sources."proto-list-1.2.4"
      sources."asap-2.0.5"
      sources."fs.realpath-1.0.0"
      sources."iferr-0.1.5"
      sources."imurmurhash-0.1.4"
      sources."fstream-ignore-1.0.5"
      sources."promzard-0.3.0"
      sources."path-array-1.0.1"
      sources."sigmund-1.0.1"
      sources."are-we-there-yet-1.0.6"
      sources."gauge-1.2.7"
      sources."delegates-1.0.0"
      sources."has-unicode-2.0.1"
      sources."lodash.pad-4.5.1"
      sources."lodash.padend-4.6.1"
      sources."lodash.padstart-4.6.1"
      sources."array-index-1.0.0"
      sources."es6-symbol-3.1.0"
      sources."d-0.1.1"
      sources."es5-ext-0.10.12"
      sources."es6-iterator-2.0.0"
      sources."is-builtin-module-1.0.0"
      sources."builtin-modules-1.1.1"
      (sources."concat-stream-1.5.2" // {
        dependencies = [
          sources."readable-stream-2.0.6"
        ];
      })
      sources."typedarray-0.0.6"
      sources."core-util-is-1.0.2"
      sources."isarray-1.0.0"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-0.10.31"
      sources."util-deprecate-1.0.2"
      sources."os-homedir-1.0.2"
      sources."os-tmpdir-1.0.2"
      sources."mute-stream-0.0.6"
      sources."debuglog-1.0.1"
      sources."readdir-scoped-modules-1.0.2"
      sources."util-extend-1.0.3"
      sources."json-parse-helpfulerror-1.0.3"
      sources."jju-1.3.0"
      (sources."bl-1.0.3" // {
        dependencies = [
          sources."readable-stream-2.0.6"
        ];
      })
      sources."caseless-0.11.0"
      sources."extend-3.0.0"
      sources."forever-agent-0.6.1"
      sources."form-data-1.0.1"
      sources."json-stringify-safe-5.0.1"
      sources."mime-types-2.1.12"
      sources."node-uuid-1.4.7"
      sources."qs-5.2.1"
      sources."tunnel-agent-0.4.3"
      sources."tough-cookie-2.2.2"
      sources."http-signature-0.11.0"
      sources."oauth-sign-0.8.2"
      sources."hawk-3.1.3"
      sources."aws-sign2-0.6.0"
      sources."stringstream-0.0.5"
      sources."combined-stream-1.0.5"
      sources."isstream-0.1.2"
      sources."har-validator-2.0.6"
      sources."async-2.0.1"
      sources."lodash-4.16.2"
      sources."mime-db-1.24.0"
      sources."assert-plus-0.1.5"
      sources."asn1-0.1.11"
      sources."ctype-0.5.3"
      sources."hoek-2.16.3"
      sources."boom-2.10.1"
      sources."cryptiles-2.0.5"
      sources."sntp-1.0.9"
      sources."delayed-stream-1.0.0"
      sources."commander-2.9.0"
      sources."is-my-json-valid-2.14.0"
      sources."pinkie-promise-2.0.1"
      sources."graceful-readlink-1.0.1"
      sources."generate-function-2.0.0"
      sources."generate-object-property-1.2.0"
      sources."jsonpointer-2.0.0"
      sources."is-property-1.0.2"
      sources."pinkie-2.0.4"
      sources."buffer-shims-1.0.0"
      sources."spdx-correct-1.0.2"
      sources."spdx-expression-parse-1.0.3"
      sources."builtins-0.0.7"
      sources."isexe-1.1.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Instantly try npm modules in REPL environment";
      homepage = "https://github.com/raine/replem#readme";
      license = "ISC";
    };
    production = true;
  };
  tern = nodeEnv.buildNodePackage {
    name = "tern";
    packageName = "tern";
    version = "0.20.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/tern/-/tern-0.20.0.tgz";
      sha1 = "5058e1ae15a121a1f421500ced0c852c11e6fb34";
    };
    dependencies = [
      sources."acorn-3.3.0"
      sources."enhanced-resolve-2.3.0"
      (sources."glob-3.2.11" // {
        dependencies = [
          sources."minimatch-0.3.0"
        ];
      })
      sources."minimatch-0.2.14"
      sources."resolve-from-2.0.0"
      sources."tapable-0.2.4"
      sources."memory-fs-0.3.0"
      sources."graceful-fs-4.1.9"
      sources."object-assign-4.1.0"
      sources."errno-0.1.4"
      sources."readable-stream-2.1.5"
      sources."prr-0.0.0"
      sources."buffer-shims-1.0.0"
      sources."core-util-is-1.0.2"
      sources."inherits-2.0.3"
      sources."isarray-1.0.0"
      sources."process-nextick-args-1.0.7"
      sources."string_decoder-0.10.31"
      sources."util-deprecate-1.0.2"
      sources."lru-cache-2.7.3"
      sources."sigmund-1.0.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A JavaScript code analyzer for deep, cross-editor language support";
      homepage = "https://github.com/ternjs/tern#readme";
      license = "MIT";
    };
    production = true;
  };
  elm-oracle = nodeEnv.buildNodePackage {
    name = "elm-oracle";
    packageName = "elm-oracle";
    version = "1.1.1";
    src = fetchurl {
      url = "https://registry.npmjs.org/elm-oracle/-/elm-oracle-1.1.1.tgz";
      sha1 = "61f6d783221b4ad08e7d101d678b9d5a67d3961c";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Query for information about values in elm source files.";
      homepage = "https://github.com/ElmCast/elm-oracle#readme";
      license = "BSD-3-Clause";
    };
    production = true;
  };
}