name: nix-build
on:
  pull_request:
  push:
jobs:
  minimal:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nixbuild/nix-quick-install-action@v8
      - uses: nixbuild/nixbuild-action@v4
        with:
          nixbuild_ssh_key: ${{ secrets.nixbuild_ssh_key }}
      - run: nix-shell --run "nix-build -A toontown -A semigroup release.nix"
